window.MODULES = window.MODULES || [];
window.MODULES.push({
  "id": "forms",
  "title": "Forms",
  "icon": "bi bi-ui-checks-grid",
  "questions": [
    {
      "id": "types-of-forms",
      "title": "Types of forms in Angular",
      "explanation": "<p>Angular provides <strong>two approaches</strong> to handling user input through forms, each suited to different use cases:</p><ul><li><strong>Template-driven forms</strong> &mdash; form logic lives in the HTML template using directives like <code>ngModel</code>. Angular infers the form model from the template. Best for simple forms.</li><li><strong>Reactive forms</strong> &mdash; form model is explicitly created in the component class using <code>FormControl</code>, <code>FormGroup</code>, and <code>FormArray</code>. More predictable, testable, and scalable for complex forms.</li></ul><p>Both approaches share the same <code>AbstractControl</code> base class and support validation, status tracking, and value access.</p>",
      "code": "// Template-driven: import FormsModule\nimport { FormsModule } from '@angular/forms';\n\n// Reactive: import ReactiveFormsModule\nimport { ReactiveFormsModule } from '@angular/forms';\n// or import specific classes\nimport { FormGroup, FormControl, Validators } from '@angular/forms';",
      "language": "typescript",
      "diagram": "<div class=\"diagram-wrap\"><p class=\"text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5\">Angular Form Approaches</p><div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\"><div class=\"bg-indigo-50 border-2 border-indigo-200 rounded-xl p-4\"><p class=\"font-bold text-indigo-700 text-center mb-2\">Template-Driven</p><ul class=\"text-xs text-slate-600 space-y-1\"><li>Logic in HTML template</li><li>Uses ngModel directive</li><li>Less code, less control</li><li>Best for simple forms</li></ul></div><div class=\"bg-emerald-50 border-2 border-emerald-200 rounded-xl p-4\"><p class=\"font-bold text-emerald-700 text-center mb-2\">Reactive</p><ul class=\"text-xs text-slate-600 space-y-1\"><li>Logic in component class</li><li>Uses FormGroup / FormControl</li><li>More control, more testable</li><li>Best for complex forms</li></ul></div></div></div>"
    },
    {
      "id": "what-are-template-driven-forms",
      "title": "What are template-driven forms?",
      "explanation": "<p><strong>Template-driven forms</strong> are Angular forms where the form structure, binding, and validation are declared directly in the HTML template using Angular directives.</p><h3>Key Directives</h3><ul><li><code>FormsModule</code> &mdash; must be imported to enable template-driven forms</li><li><code>ngModel</code> &mdash; creates two-way data binding between the input and a component property</li><li><code>ngForm</code> &mdash; auto-applied to <code>&lt;form&gt;</code> elements; exposes form-level state and methods</li><li><code>#ref=\"ngModel\"</code> &mdash; template reference to access individual control state</li></ul><h3>Showing Errors</h3><p>Use template reference variables and built-in state flags like <code>touched</code> and <code>invalid</code> to control when errors appear.</p>",
      "code": "<!-- login.component.html -->\n<form #loginForm=\"ngForm\" (ngSubmit)=\"onSubmit(loginForm)\">\n\n  <input\n    name=\"email\" type=\"email\"\n    [(ngModel)]=\"formData.email\"\n    required email\n    #emailField=\"ngModel\"\n  />\n  <div *ngIf=\"emailField.invalid && emailField.touched\">\n    <span *ngIf=\"emailField.errors?.['required']\">Email is required.</span>\n    <span *ngIf=\"emailField.errors?.['email']\">Must be a valid email.</span>\n  </div>\n\n  <input\n    name=\"password\" type=\"password\"\n    [(ngModel)]=\"formData.password\"\n    required minlength=\"6\"\n    #pwField=\"ngModel\"\n  />\n  <div *ngIf=\"pwField.invalid && pwField.touched\">\n    Password must be at least 6 characters.\n  </div>\n\n  <button type=\"submit\" [disabled]=\"loginForm.invalid\">Login</button>\n</form>",
      "language": "html",
      "diagram": "<div class=\"diagram-wrap\"><p class=\"text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5\">Template-Driven Form Flow</p><div class=\"flex flex-col items-center gap-2 max-w-sm mx-auto\"><div class=\"w-full bg-indigo-50 border-2 border-indigo-200 rounded-xl p-3 text-center\"><p class=\"text-xs font-bold text-indigo-700\">HTML Template (ngModel, ngForm)</p></div><div class=\"text-slate-300\">&darr; two-way binding &darr;</div><div class=\"w-full bg-emerald-50 border-2 border-emerald-200 rounded-xl p-3 text-center\"><p class=\"text-xs font-bold text-emerald-700\">Component Class (data object)</p></div><div class=\"text-slate-300\">&darr; Angular infers &darr;</div><div class=\"w-full bg-amber-50 border-2 border-amber-200 rounded-xl p-3 text-center\"><p class=\"text-xs font-bold text-amber-700\">FormGroup / FormControl (implicit)</p></div></div></div>"
    },
    {
      "id": "what-are-reactive-forms",
      "title": "What are reactive forms?",
      "explanation": "<p><strong>Reactive forms</strong> define the form model explicitly in the component class. The template simply binds to the existing model, giving you full programmatic control and making the form much easier to test.</p><h3>Key Classes</h3><ul><li><code>FormControl</code> &mdash; tracks value and validity of a single field</li><li><code>FormGroup</code> &mdash; a named group of controls treated as one unit</li><li><code>FormArray</code> &mdash; a variable-length array of controls (dynamic forms)</li><li><code>FormBuilder</code> &mdash; a service providing shorthand for building form models</li></ul><h3>Template Binding</h3><ul><li><code>[formGroup]=\"myForm\"</code> &mdash; binds the <code>&lt;form&gt;</code> element to a <code>FormGroup</code></li><li><code>formControlName=\"field\"</code> &mdash; binds an input to a named control inside the group</li></ul>",
      "code": "// login.component.ts\nimport { Component, OnInit } from '@angular/core';\nimport { FormGroup, FormControl, Validators } from '@angular/forms';\n\n@Component({ selector: 'app-login', templateUrl: './login.component.html' })\nexport class LoginComponent implements OnInit {\n  loginForm!: FormGroup;\n\n  ngOnInit(): void {\n    this.loginForm = new FormGroup({\n      email:    new FormControl('', [Validators.required, Validators.email]),\n      password: new FormControl('', [Validators.required, Validators.minLength(6)])\n    });\n  }\n\n  onSubmit(): void {\n    if (this.loginForm.valid) {\n      console.log(this.loginForm.value); // { email: '...', password: '...' }\n    }\n  }\n}\n\n// login.component.html\n// <form [formGroup]=\"loginForm\" (ngSubmit)=\"onSubmit()\">\n//   <input formControlName=\"email\" />\n//   <div *ngIf=\"loginForm.get('email')?.invalid && loginForm.get('email')?.touched\">\n//     <span *ngIf=\"loginForm.get('email')?.errors?.['required']\">Required.</span>\n//     <span *ngIf=\"loginForm.get('email')?.errors?.['email']\">Invalid email.</span>\n//   </div>\n//   <button type=\"submit\" [disabled]=\"loginForm.invalid\">Login</button>\n// </form>",
      "language": "typescript",
      "diagram": "<div class=\"diagram-wrap\"><p class=\"text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5\">Reactive Form Flow</p><div class=\"flex flex-col items-center gap-2 max-w-sm mx-auto\"><div class=\"w-full bg-emerald-50 border-2 border-emerald-200 rounded-xl p-3 text-center\"><p class=\"text-xs font-bold text-emerald-700\">Component Class (FormGroup defined here)</p></div><div class=\"text-slate-300\">&darr; bound via [formGroup] &darr;</div><div class=\"w-full bg-indigo-50 border-2 border-indigo-200 rounded-xl p-3 text-center\"><p class=\"text-xs font-bold text-indigo-700\">HTML Template (formControlName)</p></div><div class=\"text-slate-300\">&darr; status / value &darr;</div><div class=\"w-full bg-amber-50 border-2 border-amber-200 rounded-xl p-3 text-center\"><p class=\"text-xs font-bold text-amber-700\">AbstractControl tree (FormControl, FormGroup)</p></div></div></div>"
    },
    {
      "id": "template-vs-reactive-forms",
      "title": "Difference between template-driven and reactive forms",
      "explanation": "<p>Both approaches build on the same underlying <code>AbstractControl</code> API, but they differ in where the logic lives, how testable they are, and how well they scale.</p><table style=\"width:100%;font-size:0.75rem;border-collapse:collapse\"><thead><tr style=\"background:#f1f5f9\"><th style=\"padding:6px 8px;text-align:left;border:1px solid #e2e8f0\">Aspect</th><th style=\"padding:6px 8px;text-align:left;border:1px solid #e2e8f0\">Template-Driven</th><th style=\"padding:6px 8px;text-align:left;border:1px solid #e2e8f0\">Reactive</th></tr></thead><tbody><tr><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Form model location</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">HTML template</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Component class</td></tr><tr><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Data flow</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Two-way (ngModel)</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Explicit / reactive</td></tr><tr><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Testability</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Harder (needs DOM)</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Easier (pure TypeScript)</td></tr><tr><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Scalability</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Simple forms</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Complex / dynamic forms</td></tr><tr><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Module import</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">FormsModule</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">ReactiveFormsModule</td></tr><tr><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Async validators</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Limited</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">First-class support</td></tr><tr><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">valueChanges observable</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Not available</td><td style=\"padding:6px 8px;border:1px solid #e2e8f0\">Yes &mdash; on any control</td></tr></tbody></table>",
      "code": "// Template-driven — logic in HTML\n// <input name=\"email\" [(ngModel)]=\"email\" required email />\n\n// Reactive — logic in class\nthis.form = new FormGroup({\n  email: new FormControl('', [Validators.required, Validators.email])\n});\n\n// Reactive forms are preferred for:\n// - Dynamic form fields (FormArray)\n// - Unit testing without a DOM\n// - Complex cross-field validation\n// - Reacting to input changes via valueChanges observable",
      "language": "typescript",
      "diagram": "<div class=\"diagram-wrap\"><p class=\"text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5\">When to Use Which?</p><div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\"><div class=\"bg-indigo-50 border-2 border-indigo-200 rounded-xl p-4\"><p class=\"font-bold text-indigo-700 text-center mb-2\">Template-Driven</p><ul class=\"text-xs text-slate-600 space-y-1\"><li>Login / contact forms</li><li>Quick prototypes</li><li>Minimal validation needs</li></ul></div><div class=\"bg-emerald-50 border-2 border-emerald-200 rounded-xl p-4\"><p class=\"font-bold text-emerald-700 text-center mb-2\">Reactive</p><ul class=\"text-xs text-slate-600 space-y-1\"><li>Dynamic / wizard forms</li><li>Complex / cross-field validation</li><li>When unit testing matters</li></ul></div></div></div>"
    },
    {
      "id": "what-is-formcontrol-formgroup-formarray",
      "title": "FormControl, FormGroup and FormArray",
      "explanation": "<p>These three classes are the building blocks of Angular reactive forms, all extending <code>AbstractControl</code>.</p><h3>FormControl</h3><p>Tracks the value and validation state of a <strong>single form field</strong>. The most granular unit.</p><h3>FormGroup</h3><p>Groups multiple controls together into a single object. The group is <code>valid</code> only when <strong>all</strong> its controls are valid. Access a child with <code>.get('fieldName')</code>.</p><h3>FormArray</h3><p>An ordered array of controls &mdash; useful for <strong>dynamic / repeatable</strong> fields (e.g., a list of phone numbers or addresses). Add with <code>.push()</code>, remove with <code>.removeAt(index)</code>.</p>",
      "code": "import { FormControl, FormGroup, FormArray, Validators } from '@angular/forms';\n\n// FormControl — single field\nconst nameCtrl = new FormControl('', Validators.required);\nconsole.log(nameCtrl.value);   // ''\nconsole.log(nameCtrl.valid);   // false (required fails)\n\n// FormGroup — group of fields\nconst profileForm = new FormGroup({\n  name:  new FormControl('', Validators.required),\n  email: new FormControl('', [Validators.required, Validators.email]),\n});\nconsole.log(profileForm.value);         // { name: '', email: '' }\nconsole.log(profileForm.get('name'));   // FormControl reference\n\n// FormArray — dynamic list\nconst phonesArray = new FormArray([\n  new FormControl('555-1234'),\n  new FormControl('555-5678'),\n]);\nphoneArray.push(new FormControl('555-9999')); // add dynamically\nphoneArray.removeAt(0);                       // remove first\nconsole.log(phonesArray.length); // 2",
      "language": "typescript",
      "diagram": "<div class=\"diagram-wrap\"><p class=\"text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5\">AbstractControl Hierarchy</p><div class=\"flex flex-col items-center gap-2\"><div class=\"bg-slate-100 border border-slate-300 rounded-xl p-3 text-center\"><p class=\"text-xs font-bold text-slate-700\">AbstractControl (base class)</p></div><div class=\"text-slate-300\">&darr;</div><div class=\"grid grid-cols-3 gap-3\"><div class=\"bg-indigo-50 border-2 border-indigo-200 rounded-xl p-3 text-center\"><p class=\"text-xs font-bold text-indigo-700\">FormControl</p><p class=\"text-[10px] text-slate-500 mt-1\">single field</p></div><div class=\"bg-emerald-50 border-2 border-emerald-200 rounded-xl p-3 text-center\"><p class=\"text-xs font-bold text-emerald-700\">FormGroup</p><p class=\"text-[10px] text-slate-500 mt-1\">keyed group</p></div><div class=\"bg-amber-50 border-2 border-amber-200 rounded-xl p-3 text-center\"><p class=\"text-xs font-bold text-amber-700\">FormArray</p><p class=\"text-[10px] text-slate-500 mt-1\">dynamic list</p></div></div></div></div>"
    },
    {
      "id": "form-status-properties",
      "title": "Form status properties (pristine, dirty, touched, valid)",
      "explanation": "<p>Every <code>AbstractControl</code> exposes status properties that Angular updates automatically as the user interacts with the form. These are essential for controlling when to show error messages.</p><h3>Value &amp; Validity</h3><ul><li><code>valid</code> &mdash; all validators pass</li><li><code>invalid</code> &mdash; at least one validator fails</li><li><code>errors</code> &mdash; object of current validation errors, or <code>null</code> when valid</li><li><code>status</code> &mdash; <code>'VALID'</code>, <code>'INVALID'</code>, <code>'PENDING'</code>, or <code>'DISABLED'</code></li></ul><h3>Interaction State</h3><ul><li><code>pristine</code> &mdash; value has <strong>not</strong> been changed by the user yet</li><li><code>dirty</code> &mdash; value <strong>has</strong> been changed</li><li><code>touched</code> &mdash; control has lost focus (blur) at least once</li><li><code>untouched</code> &mdash; control has never lost focus</li></ul><p><strong>Best practice:</strong> Show errors only when <code>invalid &amp;&amp; touched</code> to avoid showing errors before the user has interacted.</p>",
      "code": "export class MyComponent {\n  emailCtrl = new FormControl('', [Validators.required, Validators.email]);\n\n  checkStatus(): void {\n    console.log(this.emailCtrl.value);    // ''\n    console.log(this.emailCtrl.valid);    // false\n    console.log(this.emailCtrl.invalid);  // true\n    console.log(this.emailCtrl.pristine); // true  (not changed yet)\n    console.log(this.emailCtrl.dirty);    // false\n    console.log(this.emailCtrl.touched);  // false (not blurred yet)\n    console.log(this.emailCtrl.errors);   // { required: true }\n    console.log(this.emailCtrl.status);   // 'INVALID'\n  }\n}\n\n// Template — show error only when the field has been interacted with:\n// <div *ngIf=\"emailCtrl.invalid && emailCtrl.touched\">\n//   <span *ngIf=\"emailCtrl.errors?.['required']\">Email is required.</span>\n//   <span *ngIf=\"emailCtrl.errors?.['email']\">Invalid email format.</span>\n// </div>",
      "language": "typescript",
      "diagram": "<div class=\"diagram-wrap\"><p class=\"text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5\">Form Control States</p><div class=\"grid grid-cols-2 gap-3 max-w-md mx-auto\"><div class=\"bg-indigo-50 border-2 border-indigo-200 rounded-xl p-3\"><p class=\"text-xs font-bold text-indigo-700\">pristine / dirty</p><p class=\"text-[10px] text-slate-500 mt-1\">Has the value been changed?</p></div><div class=\"bg-amber-50 border-2 border-amber-200 rounded-xl p-3\"><p class=\"text-xs font-bold text-amber-700\">touched / untouched</p><p class=\"text-[10px] text-slate-500 mt-1\">Has the field lost focus?</p></div><div class=\"bg-emerald-50 border-2 border-emerald-200 rounded-xl p-3\"><p class=\"text-xs font-bold text-emerald-700\">valid / invalid</p><p class=\"text-[10px] text-slate-500 mt-1\">Do all validators pass?</p></div><div class=\"bg-rose-50 border-2 border-rose-200 rounded-xl p-3\"><p class=\"text-xs font-bold text-rose-700\">status</p><p class=\"text-[10px] text-slate-500 mt-1\">VALID | INVALID | PENDING | DISABLED</p></div></div><p class=\"text-center text-xs text-slate-500 mt-4\">Show errors when: <code>invalid &amp;&amp; touched</code></p></div>"
    },
    {
      "id": "what-is-form-validation",
      "title": "Form validation and showing errors",
      "explanation": "<p><strong>Form validation</strong> ensures user input meets the required rules before submitting. Angular applies validators synchronously after every value change and updates <code>control.errors</code> accordingly.</p><h3>Applying Validators</h3><ul><li>Pass validator functions as the <strong>second argument</strong> to <code>FormControl</code></li><li>Pass multiple validators as an array</li><li><code>control.errors</code> returns <code>null</code> when valid, or an object like <code>{ required: true }</code> when invalid</li></ul><h3>Reading Error Details</h3><p>Some validators return extra metadata in the error object. For example, <code>minlength</code> returns <code>{ requiredLength, actualLength }</code>, which you can display to the user.</p>",
      "code": "this.form = new FormGroup({\n  username: new FormControl('', [\n    Validators.required,\n    Validators.minLength(3),\n    Validators.maxLength(20)\n  ]),\n  email: new FormControl('', [Validators.required, Validators.email])\n});\n\n// Template\n// <input formControlName=\"username\" />\n// <ng-container *ngIf=\"form.get('username') as ctrl\">\n//   <div *ngIf=\"ctrl.invalid && ctrl.touched\">\n//     <span *ngIf=\"ctrl.errors?.['required']\">Username is required.</span>\n//     <span *ngIf=\"ctrl.errors?.['minlength']\">\n//       Min {{ ctrl.errors?.['minlength'].requiredLength }} characters.\n//     </span>\n//     <span *ngIf=\"ctrl.errors?.['maxlength']\">\n//       Max {{ ctrl.errors?.['maxlength'].requiredLength }} characters.\n//     </span>\n//   </div>\n// </ng-container>",
      "language": "typescript",
      "diagram": "<div class=\"diagram-wrap\"><p class=\"text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5\">Validation Flow</p><div class=\"flex flex-col items-center gap-2 max-w-sm mx-auto\"><div class=\"w-full bg-indigo-50 border-2 border-indigo-200 rounded-xl p-3 text-center\"><p class=\"text-xs font-bold text-indigo-700\">User types in field</p></div><div class=\"text-slate-300\">&darr;</div><div class=\"w-full bg-amber-50 border-2 border-amber-200 rounded-xl p-3 text-center\"><p class=\"text-xs font-bold text-amber-700\">Validators run &rarr; control.errors updated</p></div><div class=\"text-slate-300\">&darr;</div><div class=\"w-full bg-emerald-50 border-2 border-emerald-200 rounded-xl p-3 text-center\"><p class=\"text-xs font-bold text-emerald-700\">Template shows error if invalid &amp;&amp; touched</p></div></div></div>"
    },
    {
      "id": "built-in-validators",
      "title": "Built-in validators in Angular",
      "explanation": "<p>Angular's <code>Validators</code> class provides synchronous validators covering the most common rules.</p><h3>Available Built-in Validators</h3><ul><li><code>Validators.required</code> &mdash; field must not be empty</li><li><code>Validators.requiredTrue</code> &mdash; field must be <code>true</code> (useful for checkboxes)</li><li><code>Validators.email</code> &mdash; must match email format</li><li><code>Validators.minLength(n)</code> &mdash; string must have at least <em>n</em> characters; error includes <code>requiredLength</code> and <code>actualLength</code></li><li><code>Validators.maxLength(n)</code> &mdash; string must have at most <em>n</em> characters</li><li><code>Validators.min(n)</code> &mdash; numeric value must be &ge; <em>n</em></li><li><code>Validators.max(n)</code> &mdash; numeric value must be &le; <em>n</em></li><li><code>Validators.pattern(regex)</code> &mdash; value must match the given regular expression</li><li><code>Validators.compose([...])</code> &mdash; combines multiple validators into one function</li></ul>",
      "code": "import { FormControl, Validators } from '@angular/forms';\n\nconst ageCtrl = new FormControl(null, [\n  Validators.required,\n  Validators.min(18),\n  Validators.max(120)\n]);\n\nconst usernameCtrl = new FormControl('', [\n  Validators.required,\n  Validators.minLength(3),\n  Validators.maxLength(20),\n  Validators.pattern('^[a-zA-Z0-9_]+$')  // alphanumeric + underscore only\n]);\n\nconst emailCtrl  = new FormControl('', [Validators.required, Validators.email]);\nconst termsCtrl  = new FormControl(false, Validators.requiredTrue);\n\n// Accessing detailed error info:\n// usernameCtrl.errors?.['minlength']?.requiredLength  -> 3\n// usernameCtrl.errors?.['minlength']?.actualLength    -> 1",
      "language": "typescript",
      "diagram": "<div class=\"diagram-wrap\"><p class=\"text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5\">Built-In Validators</p><div class=\"grid grid-cols-2 gap-2 max-w-md mx-auto text-xs\"><div class=\"bg-indigo-50 border border-indigo-200 rounded-lg p-2 text-center font-mono text-indigo-700\">required</div><div class=\"bg-indigo-50 border border-indigo-200 rounded-lg p-2 text-center font-mono text-indigo-700\">email</div><div class=\"bg-emerald-50 border border-emerald-200 rounded-lg p-2 text-center font-mono text-emerald-700\">minLength(n)</div><div class=\"bg-emerald-50 border border-emerald-200 rounded-lg p-2 text-center font-mono text-emerald-700\">maxLength(n)</div><div class=\"bg-amber-50 border border-amber-200 rounded-lg p-2 text-center font-mono text-amber-700\">min(n)</div><div class=\"bg-amber-50 border border-amber-200 rounded-lg p-2 text-center font-mono text-amber-700\">max(n)</div><div class=\"bg-purple-50 border border-purple-200 rounded-lg p-2 text-center font-mono text-purple-700\">pattern(regex)</div><div class=\"bg-purple-50 border border-purple-200 rounded-lg p-2 text-center font-mono text-purple-700\">requiredTrue</div></div></div>"
    },
    {
      "id": "how-to-create-custom-validators",
      "title": "Custom validators",
      "explanation": "<p>A <strong>custom validator</strong> is a function that takes an <code>AbstractControl</code> and returns <code>null</code> (valid) or a <code>ValidationErrors</code> object (invalid). It can be applied to individual controls or to a whole <code>FormGroup</code> for cross-field validation.</p><h3>Field-level Validator</h3><p>Validates a single control's value — e.g., no spaces allowed in a username.</p><h3>Cross-field (Group-level) Validator</h3><p>Applied to the <code>FormGroup</code> itself to compare multiple fields — e.g., password must match confirm password.</p>",
      "code": "import { AbstractControl, ValidationErrors, ValidatorFn } from '@angular/forms';\n\n// --- Field-level validator ---\nexport function noSpaceValidator(): ValidatorFn {\n  return (control: AbstractControl): ValidationErrors | null => {\n    const hasSpace = (control.value || '').includes(' ');\n    return hasSpace ? { noSpace: true } : null;\n  };\n}\n\n// --- Cross-field (group-level) validator ---\nexport function passwordMatchValidator(): ValidatorFn {\n  return (group: AbstractControl): ValidationErrors | null => {\n    const pw  = group.get('password')?.value;\n    const cpw = group.get('confirmPassword')?.value;\n    return pw === cpw ? null : { passwordMismatch: true };\n  };\n}\n\n// Usage\nthis.form = new FormGroup({\n  username:        new FormControl('', [Validators.required, noSpaceValidator()]),\n  password:        new FormControl('', Validators.required),\n  confirmPassword: new FormControl('', Validators.required),\n}, { validators: passwordMatchValidator() });\n\n// Template: check group-level error\n// <div *ngIf=\"form.errors?.['passwordMismatch']\">Passwords do not match.</div>",
      "language": "typescript",
      "diagram": "<div class=\"diagram-wrap\"><p class=\"text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5\">Custom Validator Structure</p><div class=\"max-w-md mx-auto bg-slate-50 border border-slate-200 rounded-xl p-4 font-mono text-xs space-y-2\"><p class=\"text-slate-600\">(control: AbstractControl): ValidationErrors | null</p><div class=\"border-t border-slate-200 pt-2\"><p class=\"text-emerald-600\">return null &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // valid</p><p class=\"text-rose-600\">return &#123; myError: true &#125; &nbsp; // invalid</p></div></div></div>"
    },
    {
      "id": "async-validators",
      "title": "Async validators",
      "explanation": "<p><strong>Async validators</strong> return an <code>Observable&lt;ValidationErrors | null&gt;</code> or <code>Promise</code>. They are used for checks that require a server call &mdash; such as verifying that a username is not already taken.</p><h3>Key Points</h3><ul><li>Pass async validators as the <strong>third argument</strong> to <code>FormControl</code> (after sync validators)</li><li>While an async validator is running, the control's status is <code>'PENDING'</code></li><li>Angular only runs async validators <strong>after all sync validators pass</strong>, saving unnecessary HTTP requests</li><li>The observable returned by the validator must <strong>complete</strong> &mdash; use <code>take(1)</code> or <code>first()</code> if needed</li></ul>",
      "code": "import { AbstractControl, AsyncValidatorFn, ValidationErrors } from '@angular/forms';\nimport { Observable, of } from 'rxjs';\nimport { catchError, map, switchMap, timer } from 'rxjs';\n\n// Async validator factory\nexport function uniqueUsernameValidator(userService: UserService): AsyncValidatorFn {\n  return (control: AbstractControl): Observable<ValidationErrors | null> => {\n    // timer(400) adds a debounce before firing the HTTP call\n    return timer(400).pipe(\n      switchMap(() => userService.isUsernameTaken(control.value)),\n      map(isTaken => (isTaken ? { usernameTaken: true } : null)),\n      catchError(() => of(null)) // treat server errors as valid to not block the form\n    );\n  };\n}\n\n// Usage — third argument is the async validator(s)\nthis.form = new FormGroup({\n  username: new FormControl(\n    '',\n    [Validators.required, Validators.minLength(3)], // sync\n    [uniqueUsernameValidator(this.userService)]      // async\n  )\n});\n\n// Template\n// <span *ngIf=\"form.get('username')?.status === 'PENDING'\">Checking...</span>\n// <span *ngIf=\"form.get('username')?.errors?.['usernameTaken']\">Username taken.</span>",
      "language": "typescript",
      "diagram": "<div class=\"diagram-wrap\"><p class=\"text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5\">Async Validator Flow</p><div class=\"flex flex-col items-center gap-2 max-w-sm mx-auto\"><div class=\"w-full bg-indigo-50 border-2 border-indigo-200 rounded-xl p-2 text-center text-xs font-bold text-indigo-700\">User types value</div><div class=\"text-slate-300\">&darr;</div><div class=\"w-full bg-amber-50 border-2 border-amber-200 rounded-xl p-2 text-center text-xs font-bold text-amber-700\">Sync validators pass &rarr; status: PENDING</div><div class=\"text-slate-300\">&darr;</div><div class=\"w-full bg-purple-50 border-2 border-purple-200 rounded-xl p-2 text-center text-xs font-bold text-purple-700\">HTTP call fires (after debounce)</div><div class=\"text-slate-300\">&darr;</div><div class=\"grid grid-cols-2 gap-2 w-full\"><div class=\"bg-emerald-50 border-2 border-emerald-200 rounded-xl p-2 text-center text-xs font-bold text-emerald-700\">null &rarr; VALID</div><div class=\"bg-rose-50 border-2 border-rose-200 rounded-xl p-2 text-center text-xs font-bold text-rose-700\">error obj &rarr; INVALID</div></div></div></div>"
    },
    {
      "id": "what-is-formbuilder",
      "title": "What is FormBuilder?",
      "explanation": "<p><code>FormBuilder</code> is an Angular injectable service that provides a shorter, more readable syntax for constructing reactive form models. It produces the same <code>FormControl</code>, <code>FormGroup</code>, and <code>FormArray</code> instances &mdash; just with less boilerplate.</p><h3>FormBuilder Methods</h3><ul><li><code>fb.group({...})</code> &mdash; creates a <code>FormGroup</code></li><li><code>fb.control(value, validators)</code> &mdash; creates a <code>FormControl</code></li><li><code>fb.array([...])</code> &mdash; creates a <code>FormArray</code></li></ul><p>Inside <code>fb.group()</code>, each field is a shorthand array: <code>[initialValue, syncValidators?, asyncValidators?]</code>.</p>",
      "code": "import { Component, OnInit } from '@angular/core';\nimport { FormArray, FormBuilder, FormGroup, Validators } from '@angular/forms';\n\n@Component({ selector: 'app-register', templateUrl: './register.component.html' })\nexport class RegisterComponent implements OnInit {\n  form!: FormGroup;\n\n  constructor(private fb: FormBuilder) {}\n\n  ngOnInit(): void {\n    this.form = this.fb.group({\n      name:  ['', [Validators.required, Validators.minLength(2)]],\n      email: ['', [Validators.required, Validators.email]],\n      address: this.fb.group({          // nested FormGroup\n        city: [''],\n        zip:  ['', Validators.pattern('^[0-9]{5}$')]\n      }),\n      phones: this.fb.array([           // dynamic FormArray\n        this.fb.control('', Validators.required)\n      ])\n    });\n  }\n\n  get phones(): FormArray { return this.form.get('phones') as FormArray; }\n\n  addPhone(): void { this.phones.push(this.fb.control('')); }\n\n  onSubmit(): void { console.log(this.form.value); }\n}",
      "language": "typescript",
      "diagram": "<div class=\"diagram-wrap\"><p class=\"text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5\">FormBuilder Shorthand</p><div class=\"max-w-md mx-auto bg-slate-50 border border-slate-200 rounded-xl p-4 text-xs space-y-3\"><div><p class=\"text-slate-500 mb-1\">Manual (verbose):</p><p class=\"font-mono text-slate-700\">new FormGroup(&#123; name: new FormControl('', Validators.required) &#125;)</p></div><div class=\"border-t border-slate-200 pt-3\"><p class=\"text-slate-500 mb-1\">FormBuilder (concise):</p><p class=\"font-mono text-emerald-700\">fb.group(&#123; name: ['', Validators.required] &#125;)</p></div></div></div>"
    },
    {
      "id": "valuechanges-observable",
      "title": "valueChanges observable",
      "explanation": "<p>Every <code>AbstractControl</code> exposes a <code>valueChanges</code> observable that emits every time the control's value changes. This lets you react to user input declaratively using RxJS operators.</p><h3>Common Use Cases</h3><ul><li>Live search / autocomplete with <code>debounceTime</code></li><li>Enabling or disabling other fields based on a value</li><li>Cross-field dependent logic</li><li>Real-time form preview</li></ul><p><strong>Important:</strong> Always unsubscribe in <code>ngOnDestroy</code> (or use <code>takeUntilDestroyed()</code> in Angular 16+) to avoid memory leaks.</p>",
      "code": "import { Component, OnInit, OnDestroy } from '@angular/core';\nimport { FormControl, FormGroup } from '@angular/forms';\nimport { Subject } from 'rxjs';\nimport { debounceTime, distinctUntilChanged, takeUntil } from 'rxjs/operators';\n\n@Component({ selector: 'app-search', template: '' })\nexport class SearchComponent implements OnInit, OnDestroy {\n  private destroy$ = new Subject<void>();\n\n  searchCtrl  = new FormControl('');\n  countryCtrl = new FormControl('US');\n\n  ngOnInit(): void {\n    // Live search with debounce\n    this.searchCtrl.valueChanges.pipe(\n      debounceTime(300),\n      distinctUntilChanged(),\n      takeUntil(this.destroy$)\n    ).subscribe(query => this.search(query));\n\n    // React to a single field value change\n    this.countryCtrl.valueChanges\n      .pipe(takeUntil(this.destroy$))\n      .subscribe(country => this.loadRegions(country));\n  }\n\n  ngOnDestroy(): void {\n    this.destroy$.next();\n    this.destroy$.complete();\n  }\n\n  search(query: string | null) { /* call API */ }\n  loadRegions(country: string | null) { /* call API */ }\n}",
      "language": "typescript",
      "diagram": "<div class=\"diagram-wrap\"><p class=\"text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5\">valueChanges Flow</p><div class=\"flex flex-col items-center gap-2 max-w-sm mx-auto\"><div class=\"w-full bg-indigo-50 border-2 border-indigo-200 rounded-xl p-2 text-center text-xs font-bold text-indigo-700\">User types in field</div><div class=\"text-slate-300\">&darr;</div><div class=\"w-full bg-amber-50 border-2 border-amber-200 rounded-xl p-2 text-center text-xs font-bold text-amber-700\">control.valueChanges emits new value</div><div class=\"text-slate-300\">&darr;</div><div class=\"w-full bg-purple-50 border-2 border-purple-200 rounded-xl p-2 text-center text-xs font-bold text-purple-700\">RxJS pipe (debounceTime, distinctUntilChanged...)</div><div class=\"text-slate-300\">&darr;</div><div class=\"w-full bg-emerald-50 border-2 border-emerald-200 rounded-xl p-2 text-center text-xs font-bold text-emerald-700\">subscribe callback (API call, state update)</div></div></div>"
    }
  ]
});
