window.MODULES = window.MODULES || [];
window.MODULES.push({
  "id": "testing",
  "title": "Testing",
  "icon": "bi bi-check2-circle",
  "questions": [
    {
      "id": "types-of-testing",
      "title": "Types of testing in Angular",
      "explanation": "<p>Angular applications use three layers of testing, each serving a different purpose. They're often visualised as a pyramid — many small fast tests at the base, fewer slow end-to-end tests at the top.</p><h3>Unit tests — test one thing in isolation</h3><p>A unit test tests a single function, class, or component in complete isolation from its dependencies. Dependencies are replaced with mocks or spies. These tests run in milliseconds, you can have thousands of them, and they pinpoint exactly what broke.</p><h3>Integration tests — test how parts work together</h3><p>Integration tests check that multiple real units interact correctly — for example, a component and its template, or a component and a real service (backed by an HTTP mock). In Angular, component tests created with <code>TestBed</code> are typically integration tests.</p><h3>End-to-end (E2E) tests — test the whole app from the user's perspective</h3><p>E2E tests run a real browser, navigate the actual app, click buttons, fill forms, and assert what the user sees. They're the most realistic but also the slowest and most fragile. Use them to verify critical user journeys (login, checkout, registration).</p>",
      "code": "// ─── Unit test: pure function (no Angular setup needed) ────────\nfunction add(a: number, b: number): number { return a + b; }\n\ndescribe('add', () => {\n  it('returns the sum of two numbers', () => {\n    expect(add(2, 3)).toBe(5);\n    expect(add(-1, 1)).toBe(0);\n  });\n});\n\n// ─── Unit test: pipe ────────────────────────────────────────────\ndescribe('TruncatePipe', () => {\n  const pipe = new TruncatePipe();\n\n  it('truncates text longer than the limit', () => {\n    expect(pipe.transform('Hello World', 5)).toBe('Hello...');\n  });\n\n  it('returns the full text if within limit', () => {\n    expect(pipe.transform('Hi', 5)).toBe('Hi');\n  });\n});\n\n// ─── Integration test: component + template (uses TestBed) ─────\n// Covered in the component testing question below.\n\n// ─── E2E test: user clicks through the app (Cypress) ───────────\n// cy.visit('/login');\n// cy.get('[data-cy=email]').type('user@example.com');\n// cy.get('[data-cy=password]').type('password');\n// cy.get('[data-cy=submit]').click();\n// cy.url().should('include', '/dashboard');",
      "language": "typescript"
    },
    {
      "id": "what-is-jasmine",
      "title": "What is Jasmine?",
      "explanation": "<p><strong>Jasmine</strong> is the testing framework Angular uses by default. It provides the vocabulary for describing and writing tests.</p><h3>Core keywords</h3><ul><li><code>describe('label', fn)</code> — creates a test suite (a logical group of related tests). Suites can be nested.</li><li><code>it('description', fn)</code> — a single test case (also called a 'spec'). The description should read like a sentence: \"it should return the user's full name\".</li><li><code>expect(value)</code> — creates an expectation. Chain it with a <strong>matcher</strong>.</li><li><code>beforeEach(fn)</code> — runs before every <code>it()</code> in the enclosing <code>describe()</code>. Used to reset state.</li><li><code>afterEach(fn)</code> — runs after every <code>it()</code>. Used for cleanup.</li><li><code>beforeAll(fn)</code> / <code>afterAll(fn)</code> — run once before/after all specs in a suite.</li></ul><h3>Common matchers</h3><ul><li><code>.toBe(value)</code> — strict equality (<code>===</code>)</li><li><code>.toEqual(value)</code> — deep equality (objects/arrays)</li><li><code>.toBeTruthy()</code> / <code>.toBeFalsy()</code></li><li><code>.toContain(item)</code> — array or string contains</li><li><code>.toThrow()</code> — function throws an error</li><li><code>.toHaveBeenCalled()</code> — spy was called</li><li><code>.toHaveBeenCalledWith(...args)</code> — spy was called with specific arguments</li></ul>",
      "code": "describe('AuthService', () => {\n  let service: AuthService;\n\n  beforeEach(() => {\n    service = new AuthService();   // fresh instance before each test\n  });\n\n  // ─── Basic matchers ────────────────────────────────────────\n  it('should be created', () => {\n    expect(service).toBeTruthy();   // not null/undefined\n  });\n\n  it('should return false when not logged in', () => {\n    expect(service.isLoggedIn()).toBe(false);  // strict equality\n  });\n\n  it('should return the user after login', () => {\n    const user = { id: 1, name: 'Alice', email: 'alice@example.com' };\n    service.login(user);\n    expect(service.getUser()).toEqual(user);    // deep equality\n  });\n\n  it('should include admin in roles', () => {\n    service.login({ id: 1, name: 'Admin', roles: ['user', 'admin'] });\n    expect(service.getRoles()).toContain('admin');\n  });\n\n  it('should throw when accessing user without login', () => {\n    expect(() => service.getUser()).toThrow();\n  });\n\n  afterEach(() => {\n    service.logout();   // clean up after each test\n  });\n});",
      "language": "typescript"
    },
    {
      "id": "what-is-karma",
      "title": "What is Karma?",
      "explanation": "<p><strong>Karma</strong> is a <strong>test runner</strong> — it is the tool that actually executes your Jasmine tests. Think of the division of roles like this: Jasmine writes the script (the test definitions), Karma runs the show (launches a browser and executes the tests in it).</p><h3>What Karma does</h3><ol><li>Compiles your Angular test files using the Angular CLI</li><li>Launches a browser (Chrome by default)</li><li>Loads the compiled test code in the browser</li><li>Executes all the Jasmine specs</li><li>Reports pass/fail results back to your terminal</li></ol><h3>Running tests</h3><p>Run <code>ng test</code> to start Karma in watch mode — it re-runs tests automatically on every file save. Run <code>ng test --watch=false --browsers=ChromeHeadless</code> for a single CI run without opening a browser window.</p><h3>Modern alternatives</h3><p>Karma is deprecated as of Angular 16. The Angular team recommends migrating to <strong>Jest</strong> (faster, no browser needed, great TypeScript support) or the browser-native <strong>Web Test Runner</strong>. New projects started with Angular 17+ use Jest or Web Test Runner by default.</p>",
      "code": "// ─── Run tests ─────────────────────────────────────────────────\n// ng test                                — watch mode (re-runs on save)\n// ng test --watch=false                  — single run\n// ng test --watch=false --browsers=ChromeHeadless  — CI-friendly\n// ng test --code-coverage                — generate coverage report\n\n// ─── karma.conf.js — basic setup ─────────────────────────────\nmodule.exports = function(config) {\n  config.set({\n    frameworks: ['jasmine', '@angular-devkit/build-angular'],\n    browsers: ['Chrome'],       // or 'ChromeHeadless' for CI\n    singleRun: false,           // false = watch mode\n    restartOnFileChange: true\n  });\n};\n\n// ─── Migrating to Jest (Angular 16+) ─────────────────────────\n// ng add @angular/build:jest   (official schematic)\n// Benefits of Jest:\n// — No browser window needed (faster)\n// — Snapshot testing\n// — Better error messages\n// — Parallel test execution\n// — Widely used in React/Vue communities too (familiar tooling)",
      "language": "javascript"
    },
    {
      "id": "what-is-testbed",
      "title": "What is TestBed?",
      "explanation": "<p><strong>TestBed</strong> is Angular's testing utility that creates a mini Angular application specifically for your test. It lets you configure an Angular module just for a test — declaring components, providing real or mock services, and importing modules — then creates component instances inside that environment.</p><h3>Why is it needed?</h3><p>Angular components are not plain classes you can just instantiate with <code>new</code>. They have templates, dependency injection, and lifecycle hooks that all require Angular's environment to work. TestBed provides that environment in a controlled, test-safe way.</p><h3>Key TestBed methods</h3><ul><li><code>TestBed.configureTestingModule({ declarations, providers, imports })</code> — sets up the testing module. Call in <code>beforeEach()</code>.</li><li><code>TestBed.createComponent(MyComponent)</code> — creates an instance of the component and returns a <code>ComponentFixture</code>.</li><li><code>TestBed.inject(MyService)</code> — gets an instance of a service from the testing module's injector.</li></ul><h3>ComponentFixture</h3><p>The fixture gives you access to the component instance (<code>fixture.componentInstance</code>), its root DOM element (<code>fixture.nativeElement</code>), and Angular's debug element (<code>fixture.debugElement</code>). Call <code>fixture.detectChanges()</code> to run change detection and update the DOM.</p>",
      "code": "import { TestBed, ComponentFixture } from '@angular/core/testing';\nimport { UserCardComponent } from './user-card.component';\nimport { UserService } from './user.service';\nimport { CommonModule } from '@angular/common';\n\ndescribe('UserCardComponent', () => {\n  let fixture: ComponentFixture<UserCardComponent>;\n  let component: UserCardComponent;\n  let mockUserService: jasmine.SpyObj<UserService>;\n\n  beforeEach(async () => {\n    // Create a spy object — all methods exist but do nothing by default\n    mockUserService = jasmine.createSpyObj('UserService', ['getUser', 'updateUser']);\n\n    await TestBed.configureTestingModule({\n      imports: [\n        UserCardComponent,   // standalone component — import, don't declare\n        CommonModule\n      ],\n      providers: [\n        // Replace the real UserService with our mock\n        { provide: UserService, useValue: mockUserService }\n      ]\n    }).compileComponents();\n\n    fixture = TestBed.createComponent(UserCardComponent);\n    component = fixture.componentInstance;\n  });\n\n  it('should create the component', () => {\n    expect(component).toBeTruthy();\n  });\n\n  it('should render the user name in the template', () => {\n    component.user = { id: 1, name: 'Alice', email: 'alice@example.com' };\n    fixture.detectChanges();   // run CD to update the DOM\n\n    const h2: HTMLElement = fixture.nativeElement.querySelector('h2');\n    expect(h2.textContent).toContain('Alice');\n  });\n});",
      "language": "typescript"
    },
    {
      "id": "how-to-test-services",
      "title": "How to test services?",
      "explanation": "<p>Services that don't depend on Angular-specific features (no HTTP, no DOM, no DI) can be tested with a simple <code>new ServiceClass()</code>. For services that use <code>HttpClient</code>, Angular provides <code>HttpClientTestingModule</code> and <code>HttpTestingController</code> to mock HTTP requests without hitting a real server.</p><h3>Testing approach for services</h3><ol><li>Provide the service via <code>TestBed</code></li><li>Provide <code>HttpClientTestingModule</code> instead of <code>HttpClientModule</code></li><li>Inject <code>HttpTestingController</code> to control mock requests</li><li>Call the service method</li><li>Flush the mock request with test data</li><li>Assert the result</li></ol><h3>Spies for dependencies</h3><p>If your service depends on another service, use <code>jasmine.createSpyObj()</code> to replace the dependency with a mock that records calls and returns controlled values.</p>",
      "code": "import { TestBed } from '@angular/core/testing';\nimport { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';\nimport { UsersService, User } from './users.service';\n\ndescribe('UsersService', () => {\n  let service: UsersService;\n  let httpMock: HttpTestingController;\n\n  beforeEach(() => {\n    TestBed.configureTestingModule({\n      imports: [HttpClientTestingModule],    // replaces real HttpClient with a mock\n      providers: [UsersService]\n    });\n    service  = TestBed.inject(UsersService);\n    httpMock = TestBed.inject(HttpTestingController);\n  });\n\n  afterEach(() => {\n    httpMock.verify();  // fail if any HTTP requests were made but not flushed\n  });\n\n  it('should GET all users and return them', () => {\n    const mockUsers: User[] = [\n      { id: 1, name: 'Alice', email: 'alice@example.com' },\n      { id: 2, name: 'Bob',   email: 'bob@example.com' }\n    ];\n\n    service.getAll().subscribe(users => {\n      expect(users.length).toBe(2);\n      expect(users[0].name).toBe('Alice');\n    });\n\n    // Expect exactly one GET request to this URL\n    const req = httpMock.expectOne('/api/users');\n    expect(req.request.method).toBe('GET');\n\n    // Flush: provide the mock response — this triggers the subscribe callback above\n    req.flush(mockUsers);\n  });\n\n  it('should handle a 404 error', () => {\n    service.getById(999).subscribe({\n      next:  ()    => fail('should have errored'),\n      error: (err) => expect(err.status).toBe(404)\n    });\n\n    const req = httpMock.expectOne('/api/users/999');\n    req.flush('Not Found', { status: 404, statusText: 'Not Found' });\n  });\n\n  it('should POST a new user', () => {\n    const newUser = { name: 'Charlie', email: 'charlie@example.com' };\n    const created = { id: 3, ...newUser };\n\n    service.create(newUser).subscribe(user => {\n      expect(user.id).toBe(3);\n      expect(user.name).toBe('Charlie');\n    });\n\n    const req = httpMock.expectOne('/api/users');\n    expect(req.request.method).toBe('POST');\n    expect(req.request.body).toEqual(newUser);\n    req.flush(created);\n  });\n});",
      "language": "typescript"
    },
    {
      "id": "how-to-test-components",
      "title": "How to test components?",
      "explanation": "<p>Component testing verifies both the <strong>component class logic</strong> and the <strong>template rendering</strong>. You use <code>TestBed</code> to create the component, interact with it via the fixture, and assert what appears in the DOM.</p><h3>Key steps</h3><ol><li>Configure <code>TestBed</code> with the component and any mocked dependencies</li><li>Create the component fixture</li><li>Set <code>@Input()</code> values and call <code>fixture.detectChanges()</code></li><li>Query the DOM using <code>fixture.nativeElement.querySelector()</code> or <code>fixture.debugElement</code></li><li>Simulate user interactions with <code>element.click()</code> or <code>element.dispatchEvent()</code></li><li>Call <code>detectChanges()</code> again after interactions and assert the updated DOM</li></ol><h3>Spies on services</h3><p>Replace real services with spies so tests don't depend on network calls. Use <code>jasmine.createSpyObj()</code> and configure each spy's return value with <code>.and.returnValue()</code>.</p>",
      "code": "import { TestBed, ComponentFixture } from '@angular/core/testing';\nimport { of, throwError } from 'rxjs';\nimport { LoginComponent } from './login.component';\nimport { AuthService } from './auth.service';\nimport { Router } from '@angular/router';\nimport { ReactiveFormsModule } from '@angular/forms';\n\ndescribe('LoginComponent', () => {\n  let fixture: ComponentFixture<LoginComponent>;\n  let component: LoginComponent;\n  let authSpy: jasmine.SpyObj<AuthService>;\n  let routerSpy: jasmine.SpyObj<Router>;\n\n  beforeEach(async () => {\n    authSpy   = jasmine.createSpyObj('AuthService', ['login']);\n    routerSpy = jasmine.createSpyObj('Router', ['navigate']);\n\n    await TestBed.configureTestingModule({\n      imports: [LoginComponent, ReactiveFormsModule],\n      providers: [\n        { provide: AuthService, useValue: authSpy },\n        { provide: Router,      useValue: routerSpy }\n      ]\n    }).compileComponents();\n\n    fixture   = TestBed.createComponent(LoginComponent);\n    component = fixture.componentInstance;\n    fixture.detectChanges();   // trigger ngOnInit, render template\n  });\n\n  it('should render the login form', () => {\n    const form = fixture.nativeElement.querySelector('form');\n    expect(form).toBeTruthy();\n  });\n\n  it('should disable the submit button when form is invalid', () => {\n    const button: HTMLButtonElement = fixture.nativeElement.querySelector('[type=\"submit\"]');\n    // Form is empty — should be disabled\n    expect(button.disabled).toBe(true);\n  });\n\n  it('should call AuthService.login with form values on submit', () => {\n    authSpy.login.and.returnValue(of({ id: 1, name: 'Alice' }));  // mock success\n\n    // Fill the form\n    component.form.setValue({ email: 'alice@example.com', password: 'password123' });\n    fixture.detectChanges();\n\n    // Submit the form\n    fixture.nativeElement.querySelector('form').dispatchEvent(new Event('submit'));\n    fixture.detectChanges();\n\n    expect(authSpy.login).toHaveBeenCalledWith('alice@example.com', 'password123');\n    expect(routerSpy.navigate).toHaveBeenCalledWith(['/dashboard']);\n  });\n\n  it('should show an error message on login failure', () => {\n    authSpy.login.and.returnValue(throwError(() => new Error('Invalid credentials')));\n\n    component.form.setValue({ email: 'wrong@example.com', password: 'bad' });\n    fixture.nativeElement.querySelector('form').dispatchEvent(new Event('submit'));\n    fixture.detectChanges();\n\n    const error: HTMLElement = fixture.nativeElement.querySelector('.error-message');\n    expect(error.textContent).toContain('Invalid credentials');\n  });\n});",
      "language": "typescript"
    },
    {
      "id": "what-is-e2e-testing",
      "title": "What is end-to-end testing?",
      "explanation": "<p><strong>End-to-end (E2E) tests</strong> run a real browser and simulate a real user interacting with your full application — frontend, routing, HTTP calls to a backend, database. They test the entire stack top to bottom.</p><h3>What unit tests miss</h3><p>Unit tests test each piece in isolation with mocks. E2E tests find bugs that only appear when everything runs together: a CSS overlay blocking a button, a redirect loop caused by guards interacting, a race condition between two API calls, a deployment misconfiguration.</p><h3>Modern E2E tools</h3><ul><li><strong>Cypress</strong> — the most popular Angular E2E tool. Runs in the browser, has an interactive test runner, excellent debugging tools, time-travel screenshots. Recommended by the Angular team.</li><li><strong>Playwright</strong> — cross-browser (Chrome, Firefox, Safari), very fast, headless by default. Excellent for CI pipelines.</li><li><strong>Protractor</strong> — the original Angular E2E tool. Now deprecated. Do not start new projects with Protractor.</li></ul><h3>Best practices</h3><p>Use <code>data-cy</code> (Cypress) or <code>data-testid</code> attributes on elements you need to select in tests. Never use CSS classes or text content as selectors — they change as the UI evolves.</p>",
      "code": "// ─── Cypress E2E test — complete login flow ────────────────────\ndescribe('Login Flow', () => {\n  beforeEach(() => {\n    cy.visit('/login');\n  });\n\n  it('should redirect to dashboard after successful login', () => {\n    // Fill the form using data-cy attributes (stable selectors)\n    cy.get('[data-cy=email-input]').type('alice@example.com');\n    cy.get('[data-cy=password-input]').type('password123');\n    cy.get('[data-cy=login-button]').click();\n\n    // Assert the user landed on the dashboard\n    cy.url().should('include', '/dashboard');\n    cy.get('[data-cy=welcome-message]').should('contain', 'Welcome, Alice');\n  });\n\n  it('should show an error for invalid credentials', () => {\n    cy.get('[data-cy=email-input]').type('wrong@example.com');\n    cy.get('[data-cy=password-input]').type('wrongpassword');\n    cy.get('[data-cy=login-button]').click();\n\n    cy.get('[data-cy=error-message]').should('be.visible');\n    cy.get('[data-cy=error-message]').should('contain', 'Invalid credentials');\n    cy.url().should('include', '/login');  // should NOT have navigated away\n  });\n\n  it('should keep submit button disabled when form is empty', () => {\n    cy.get('[data-cy=login-button]').should('be.disabled');\n  });\n});\n\n// Angular component template — add data-cy attributes:\n// <input data-cy=\"email-input\"    formControlName=\"email\" />\n// <input data-cy=\"password-input\" formControlName=\"password\" type=\"password\" />\n// <button data-cy=\"login-button\"  type=\"submit\">Login</button>\n// <p data-cy=\"error-message\">{{ errorMsg }}</p>",
      "language": "typescript"
    },
    {
      "id": "what-is-protractor",
      "title": "Protractor (deprecated) and modern alternatives",
      "explanation": "<p><strong>Protractor</strong> was Angular's original E2E testing framework, built by the Angular team on top of Selenium WebDriver. It had special Angular-aware waiting logic that knew when the framework had finished processing (waiting for Angular's zone to become stable).</p><h3>Why it was deprecated</h3><p>Protractor had several problems that modern tools solve better: slow setup, flaky tests due to timing issues, poor debugging experience, and no active development. In 2022 the Angular team officially deprecated Protractor.</p><h3>What to use instead</h3><ul><li><strong>Cypress</strong> — <code>ng add @cypress/schematic</code>. Best developer experience, interactive test runner with time-travel screenshots. Most popular choice for Angular teams.</li><li><strong>Playwright</strong> — <code>npm init playwright</code>. Fastest option, true cross-browser support (Chrome, Firefox, Safari), excellent for CI. Gaining popularity quickly.</li><li><strong>Nightwatch.js</strong> — officially supported by Angular, added via <code>ng add @nightwatch/schematics</code></li></ul><h3>Cypress vs Playwright</h3><p>Choose <strong>Cypress</strong> if developer experience and debugging matter most. Choose <strong>Playwright</strong> if cross-browser testing, speed, and CI performance are the priority.</p>",
      "code": "// ─── Protractor (LEGACY — do not use for new projects) ─────────\n// element(by.id('submit')).click();\n// expect(browser.getCurrentUrl()).toContain('/dashboard');\n// browser.waitForAngular();\n\n// ─── Cypress setup (recommended) ──────────────────────────────\n// npm install cypress --save-dev\n// OR with Angular schematic:\n// ng add @cypress/schematic\n\n// Run Cypress:\n// npx cypress open    ← interactive, watch mode with time-travel screenshots\n// npx cypress run     ← headless, for CI pipelines\n\n// ─── Playwright setup ─────────────────────────────────────────\n// npm init playwright@latest\n// npx playwright install   (downloads browsers)\n// npx playwright test      (run all tests)\n\n// playwright.config.ts — example for an Angular app\nimport { defineConfig } from '@playwright/test';\nexport default defineConfig({\n  testDir: './e2e',\n  use: {\n    baseURL: 'http://localhost:4200',\n    trace: 'on-first-retry',     // record traces on failure for debugging\n    screenshot: 'only-on-failure'\n  },\n  webServer: {\n    command: 'ng serve',\n    url: 'http://localhost:4200',\n    reuseExistingServer: !process.env['CI']  // reuse ng serve in dev mode\n  }\n});\n\n// Playwright test example:\nimport { test, expect } from '@playwright/test';\n\ntest('user can log in', async ({ page }) => {\n  await page.goto('/login');\n  await page.fill('[data-testid=email]',    'alice@example.com');\n  await page.fill('[data-testid=password]', 'password123');\n  await page.click('[data-testid=submit]');\n  await expect(page).toHaveURL(/dashboard/);\n  await expect(page.locator('h1')).toContainText('Welcome');\n});",
      "language": "typescript"
    }
  ]
});
