window.MODULES = window.MODULES || [];
window.MODULES.push({
  "id": "pwa",
  "title": "Progressive Web Apps (PWA)",
  "icon": "bi bi-phone-vibrate",
  "questions": [
    {
      "id": "what-is-pwa",
      "title": "What is a Progressive Web App (PWA)?",
      "explanation": "\n          <p>A <strong>Progressive Web App (PWA)</strong> is a web application that uses modern browser APIs to deliver an experience that feels like a native mobile or desktop app — installable on the home screen, capable of running offline, and able to receive push notifications. The word \"progressive\" means it enhances progressively: the base experience is still a normal website, and the app-like features layer on top for users whose browsers support them.</p>\n\n          <p>The value proposition is significant for the right applications. A traditional native app requires the user to visit an app store, download hundreds of megabytes, grant permissions, and wait for installation. A PWA is visited via a URL — the first visit loads in seconds, the app can be installed with a single tap, and subsequent visits work from cache even without a network connection.</p>\n\n          <h3>The Three Required Pillars</h3>\n          <p><strong>HTTPS</strong> — PWAs require a secure origin. Service workers (the technology behind offline capability) only register over HTTPS or localhost. This is a security requirement, not just a recommendation.</p>\n          <p><strong>Web App Manifest</strong> — A JSON file that describes the app: its name, icons, theme color, start URL, and display mode. The browser reads this to know how to install the app and what it should look like when launched from the home screen.</p>\n          <p><strong>Service Worker</strong> — A JavaScript file that runs in the background, separate from the main thread, intercepting network requests and serving cached responses. This is what makes offline mode and fast loads possible.</p>\n        ",
      "code": "// PWAs combine three technologies to feel native:\n\n// 1. HTTPS: required for service workers\n//    Deploy to https://myapp.com (localhost exempt for development)\n\n// 2. Web App Manifest: tells the browser how to install the app\n// manifest.webmanifest:\n{\n  \"name\": \"My Shop\",\n  \"short_name\": \"Shop\",\n  \"description\": \"The best products, delivered fast.\",\n  \"start_url\": \"/\",\n  \"display\": \"standalone\",      // hides browser chrome when installed\n  \"background_color\": \"#ffffff\",\n  \"theme_color\": \"#6366f1\",\n  \"icons\": [\n    { \"src\": \"icons/icon-192.png\", \"sizes\": \"192x192\", \"type\": \"image/png\" },\n    { \"src\": \"icons/icon-512.png\", \"sizes\": \"512x512\", \"type\": \"image/png\",\n      \"purpose\": \"maskable\" }\n  ]\n}\n\n// 3. Service Worker: intercepts network requests\n// Angular's @angular/service-worker generates and manages this for you.",
      "language": "json"
    },
    {
      "id": "how-to-convert-angular-to-pwa",
      "title": "How to convert an Angular app to a PWA?",
      "explanation": "\n          <p>Angular makes PWA conversion a one-command operation via its CLI schematic. The <code>ng add @angular/pwa</code> command installs the necessary package and configures everything automatically — you do not need to manually write a service worker or create a manifest from scratch.</p>\n\n          <h3>What ng add @angular/pwa Does</h3>\n          <p>The schematic modifies your project in several ways: it installs <code>@angular/service-worker</code>, enables <code>serviceWorker: true</code> in the production configuration of <code>angular.json</code>, imports <code>ServiceWorkerModule</code> (or calls <code>provideServiceWorker()</code> in standalone apps), creates <code>src/manifest.webmanifest</code> with sensible defaults, adds a link to the manifest in <code>index.html</code>, creates <code>ngsw-config.json</code> which defines the caching strategy, and generates placeholder icons in <code>src/assets/icons/</code>.</p>\n\n          <h3>Important: Service Workers Only Work in Production Builds</h3>\n          <p>Angular's service worker is only activated in production builds. Running <code>ng serve</code> does not register a service worker because development mode reloads files constantly, which would conflict with caching. To test PWA behavior locally, run <code>ng build</code> and serve the <code>dist/</code> folder with a local HTTP server like <code>http-server</code>.</p>\n        ",
      "code": "# ---- Step 1: Add PWA support ----\nng add @angular/pwa\n# Installs @angular/service-worker, creates manifest.webmanifest,\n# creates ngsw-config.json, updates angular.json and index.html\n\n# ---- Step 2: Build for production (service worker only activates here) ----\nng build --configuration production\n\n# ---- Step 3: Test locally with a static server ----\nnpx http-server dist/my-app -p 8080\n# Open http://localhost:8080 in Chrome\n# DevTools → Application → Service Workers: should show 'Activated and running'\n# DevTools → Application → Manifest: should show app details\n\n# ---- What gets added to angular.json ----\n# \"serviceWorker\": true       <- activates SW in production build\n# \"ngswConfigPath\": \"ngsw-config.json\"  <- points to caching config\n\n# ---- What gets added to main.ts (standalone) ----\n# bootstrapApplication(AppComponent, {\n#   providers: [\n#     provideServiceWorker('ngsw-worker.js', {\n#       enabled: !isDevMode(),\n#       registrationStrategy: 'registerWhenStable:30000'\n#     })\n#   ]\n# })",
      "language": "bash"
    },
    {
      "id": "what-is-service-worker",
      "title": "What is a service worker?",
      "explanation": "\n          <p>A <strong>service worker</strong> is a JavaScript file that runs in the browser in a separate background thread — independent from the main page thread, with no access to the DOM. Its primary job in a PWA is to act as a <strong>programmable network proxy</strong>: it intercepts every outgoing fetch request from the page, decides whether to serve the response from the cache or fetch it from the network, and can update cached files in the background.</p>\n\n          <h3>The Service Worker Lifecycle</h3>\n          <p>A service worker goes through three states. <strong>Installation</strong> — when the browser first registers the service worker, it runs the install event. Angular's service worker uses this to prefetch and cache all assets defined in <code>ngsw-config.json</code>. <strong>Activation</strong> — once installed, the service worker waits for all existing pages using the old version to close, then takes control. Angular's SwUpdate service provides hooks to detect and handle this. <strong>Active</strong> — the service worker intercepts all fetch requests from pages under its scope.</p>\n\n          <h3>Angular's ngsw-worker.js</h3>\n          <p>Angular generates its service worker file (<code>ngsw-worker.js</code>) automatically during <code>ng build</code>. You configure it by editing <code>ngsw-config.json</code> — you never write the service worker script itself. The generated worker implements Angular's caching strategy, asset versioning, and update notification protocol.</p>\n\n          <h3>Caching Strategies</h3>\n          <p><strong>prefetch</strong> — downloads all matching files when the service worker installs. Use this for your app shell (HTML, JS, CSS) — critical files that must be available offline immediately. <strong>lazy</strong> — downloads files on first request and then serves from cache thereafter. Use this for secondary assets that are not critical for the initial page load.</p>\n        ",
      "code": "// ---- ngsw-config.json: configures what the service worker caches ----\n{\n  \"index\": \"/index.html\",\n  \"assetGroups\": [\n    {\n      \"name\": \"app-shell\",\n      \"installMode\": \"prefetch\",   // cache immediately on SW install\n      \"updateMode\": \"prefetch\",    // update immediately when new version detected\n      \"resources\": {\n        \"files\": [\n          \"/favicon.ico\",\n          \"/index.html\",\n          \"/manifest.webmanifest\",\n          \"/*.css\",\n          \"/*.js\"\n        ]\n      }\n    },\n    {\n      \"name\": \"assets\",\n      \"installMode\": \"lazy\",       // cache on first request\n      \"updateMode\": \"prefetch\",\n      \"resources\": {\n        \"files\": [\n          \"/assets/**\",\n          \"/*.(svg|cur|jpg|jpeg|png|apng|webp|avif|gif|otf|ttf|woff|woff2|ani)\"\n        ]\n      }\n    }\n  ],\n  \"dataGroups\": [\n    {\n      \"name\": \"api-freshness\",\n      \"urls\": [\"/api/products\"],\n      \"cacheConfig\": {\n        \"strategy\": \"freshness\",    // network first, cache as fallback\n        \"maxSize\": 100,\n        \"maxAge\": \"3d\",             // cache for 3 days\n        \"timeout\": \"10s\"            // fall back to cache after 10s timeout\n      }\n    },\n    {\n      \"name\": \"api-performance\",\n      \"urls\": [\"/api/categories\"],\n      \"cacheConfig\": {\n        \"strategy\": \"performance\",  // cache first, refresh in background\n        \"maxSize\": 10,\n        \"maxAge\": \"1h\"\n      }\n    }\n  ]\n}",
      "language": "json"
    },
    {
      "id": "what-is-manifest-json",
      "title": "What is the Web App Manifest?",
      "explanation": "\n          <p>The <strong>Web App Manifest</strong> (<code>manifest.webmanifest</code> in Angular projects) is a JSON file that provides the browser with information about your application — what to name it, what icons to use, what color the title bar should be, and how the app should display when launched from the home screen. The browser reads the manifest to power the \"Add to Home Screen\" or \"Install App\" prompt.</p>\n\n          <h3>Key Fields</h3>\n          <p><code>name</code> — the full application name shown during installation and on splash screens. <code>short_name</code> — the abbreviated name shown under the home screen icon where space is limited. <code>start_url</code> — the URL that opens when the app is launched from the home screen. Usually <code>/</code> but can be a specific page. <code>display</code> — how the app looks when launched: <code>standalone</code> hides the browser address bar and navigation, making it feel like a native app; <code>fullscreen</code> hides everything including the status bar; <code>browser</code> opens in a regular browser tab. <code>theme_color</code> — the color of the browser's address bar and status bar. <code>background_color</code> — the splash screen background color shown before the app loads.</p>\n\n          <h3>Icons and Maskable Icons</h3>\n          <p>You must provide icons at multiple sizes — at minimum 192×192 and 512×512 pixels. The <code>purpose: \"maskable\"</code> flag marks an icon as safe to crop within various shape masks (circle on Android, rounded square on iOS). Maskable icons have extra padding around the content so the subject is not cut off when the OS applies its mask.</p>\n        ",
      "code": "// src/manifest.webmanifest (generated by ng add @angular/pwa, customize from here)\n{\n  \"name\": \"My Angular Shop\",\n  \"short_name\": \"Shop\",\n  \"description\": \"Shop the best products with fast delivery.\",\n  \"start_url\": \"/\",\n  \"scope\": \"/\",\n  \"display\": \"standalone\",\n  \"orientation\": \"portrait-primary\",\n  \"background_color\": \"#ffffff\",\n  \"theme_color\": \"#6366f1\",\n  \"lang\": \"en-US\",\n  \"categories\": [\"shopping\", \"lifestyle\"],\n  \"screenshots\": [\n    { \"src\": \"screenshots/home.png\", \"sizes\": \"1280x720\", \"type\": \"image/png\" }\n  ],\n  \"icons\": [\n    { \"src\": \"assets/icons/icon-72x72.png\",   \"sizes\": \"72x72\",   \"type\": \"image/png\" },\n    { \"src\": \"assets/icons/icon-96x96.png\",   \"sizes\": \"96x96\",   \"type\": \"image/png\" },\n    { \"src\": \"assets/icons/icon-128x128.png\", \"sizes\": \"128x128\", \"type\": \"image/png\" },\n    { \"src\": \"assets/icons/icon-192x192.png\", \"sizes\": \"192x192\", \"type\": \"image/png\" },\n    { \"src\": \"assets/icons/icon-512x512.png\", \"sizes\": \"512x512\", \"type\": \"image/png\" },\n    {\n      \"src\": \"assets/icons/icon-512x512.png\",\n      \"sizes\": \"512x512\",\n      \"type\": \"image/png\",\n      \"purpose\": \"maskable\"  // safe to crop into a circle/rounded-square on Android\n    }\n  ]\n}\n\n// Linked in index.html (added automatically by ng add @angular/pwa):\n// <link rel=\"manifest\" href=\"manifest.webmanifest\" />",
      "language": "json"
    },
    {
      "id": "sw-update-management",
      "title": "Managing app updates with SwUpdate",
      "explanation": "\n          <p>One of the most important operational concerns with PWAs is <strong>update management</strong>. Because service workers cache your app shell aggressively, users may run an old version of your app for days or weeks after you deploy a new one. Angular's <code>SwUpdate</code> service provides a reactive API for detecting, prompting, and applying updates.</p>\n\n          <h3>How Angular Detects Updates</h3>\n          <p>When a user visits the app, the service worker checks the server for a new <code>ngsw.json</code> manifest (generated at build time). If the manifest has changed, there is a new version available. The service worker downloads the new files in the background without disrupting the current session. Once everything is downloaded, it notifies the app through <code>SwUpdate.versionUpdates</code>.</p>\n\n          <h3>Version Update Events</h3>\n          <p>The <code>versionUpdates</code> observable emits events of different types: <code>VERSION_DETECTED</code> (new version is being downloaded), <code>VERSION_READY</code> (new version is downloaded and ready to activate), <code>VERSION_INSTALLATION_FAILED</code> (download failed), and <code>NO_NEW_VERSION_DETECTED</code> (app is up to date). Handle <code>VERSION_READY</code> to show a \"New version available\" banner and let users decide when to update.</p>\n\n          <h3>Unrecoverable State</h3>\n          <p>Sometimes a service worker gets into a state where it cannot serve a requested resource (e.g., a cached chunk is from an old version and the server no longer has the corresponding API format). Angular's <code>SwUpdate.unrecoverable</code> observable fires in this case. The correct response is to reload the page to force a fresh download.</p>\n        ",
      "code": "import { Component, inject, OnInit } from '@angular/core';\nimport { SwUpdate, VersionReadyEvent } from '@angular/service-worker';\nimport { filter } from 'rxjs/operators';\n\n@Component({\n  selector: 'app-update-notifier',\n  standalone: true,\n  template: `\n    <div *ngIf=\"updateAvailable\" class=\"update-banner\">\n      <span>A new version is available!</span>\n      <button (click)=\"activateUpdate()\">Update Now</button>\n      <button (click)=\"updateAvailable = false\">Later</button>\n    </div>\n  `\n})\nexport class UpdateNotifierComponent implements OnInit {\n  private swUpdate = inject(SwUpdate);\n  updateAvailable = false;\n\n  ngOnInit(): void {\n    if (!this.swUpdate.isEnabled) {\n      console.log('Service worker disabled (dev mode)');\n      return;\n    }\n\n    // Listen for a new version that is ready to activate\n    this.swUpdate.versionUpdates\n      .pipe(filter((evt): evt is VersionReadyEvent => evt.type === 'VERSION_READY'))\n      .subscribe(evt => {\n        console.log(`Current version: ${evt.currentVersion.hash}`);\n        console.log(`New version: ${evt.latestVersion.hash}`);\n        this.updateAvailable = true;\n      });\n\n    // Handle unrecoverable state — reload to recover\n    this.swUpdate.unrecoverable.subscribe(event => {\n      console.error('Unrecoverable SW state:', event.reason);\n      // Must reload — the app cannot continue in this state\n      if (confirm('Application error. Reload to recover?')) {\n        window.location.reload();\n      }\n    });\n\n    // Periodically check for updates (every 6 hours)\n    setInterval(() => this.swUpdate.checkForUpdate(), 6 * 60 * 60 * 1000);\n  }\n\n  async activateUpdate(): Promise<void> {\n    await this.swUpdate.activateUpdate();\n    // Reload to apply the new version\n    document.location.reload();\n  }\n}",
      "language": "typescript"
    }
  ]
});
