window.MODULES = window.MODULES || [];
window.MODULES.push({
  "id": "signals",
  "title": "Signals (Angular 16+)",
  "icon": "bi bi-reception-4",
  "questions": [
    {
      id: "angular-22-standard-signals-upgrade",
      title: "Angular 22 standard for signals",
      explanation: `
        <div class="analogy-box">
          <svg class="analogy-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
          <div class="analogy-body">
            <p class="analogy-label">Think of it like</p>
            <p class="analogy-text">A <strong>live spreadsheet</strong> replacing a stack of paper reports that someone has to manually re-tally every time a number changes. In the old world (Zone.js + change detection), Angular re-checked the whole worksheet on every event just in case something moved. With signals, each cell knows exactly which other cells depend on it &mdash; change one number and only the cells that actually reference it recalculate, instantly and automatically.</p>
          </div>
        </div>
        <p>In Angular 22-ready code, signals are the default primitive for synchronous UI state. Use writable signals for local state, <code>computed()</code> for derived state, <code>effect()</code> only for side effects, and RxJS interop when state crosses into async streams like HTTP, router params, or form changes. This isn't just style preference &mdash; signals are precisely what makes <strong>zoneless change detection</strong> viable, and zoneless is the default for new CLI-generated apps in Angular 22.</p>
        <h3>Modern signals checklist</h3>
        <ul>
          <li>Read signals in templates by calling them: <code>count()</code>.</li>
          <li>Update signals with <code>set()</code> and <code>update()</code> &mdash; know the difference between the two.</li>
          <li>Keep derived state in <code>computed()</code>, not template methods.</li>
          <li>Use <code>input()</code>, <code>output()</code>, and <code>model()</code> for modern component APIs.</li>
          <li>Expose readonly signals from services with <code>.asReadonly()</code>.</li>
          <li>Use <code>toSignal()</code> and <code>toObservable()</code> at RxJS boundaries.</li>
          <li>Reach for stable <code>resource()</code>/<code>rxResource()</code>/<code>httpResource()</code> for async data instead of hand-rolled loading flags.</li>
        </ul>
      `,
      code: `@Injectable({ providedIn: 'root' })
export class CounterStore {
  private readonly countState = signal(0);

  readonly count = this.countState.asReadonly();
  readonly doubled = computed(() => this.count() * 2);

  increment(): void {
    this.countState.update(value => value + 1);
  }
}

@Component({
  selector: 'app-counter-button',
  template: '<button (click)="store.increment()">{{ store.count() }}</button>'
})
export class CounterButtonComponent {
  readonly store = inject(CounterStore);
}`,
      language: "typescript",
      diagram: `<div class="diagram-wrap"><p class="text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5">Signals — Why Angular 22 Leans On Them</p><div class="grid grid-cols-2 md:grid-cols-3 gap-3 max-w-2xl mx-auto text-xs"><div class="bg-indigo-50 border border-indigo-200 rounded-lg p-3 text-center"><p class="font-bold text-indigo-700">signal()</p><p class="text-slate-500 mt-1">writable state</p></div><div class="bg-emerald-50 border border-emerald-200 rounded-lg p-3 text-center"><p class="font-bold text-emerald-700">computed()</p><p class="text-slate-500 mt-1">derived, memoized</p></div><div class="bg-amber-50 border border-amber-200 rounded-lg p-3 text-center"><p class="font-bold text-amber-700">effect()</p><p class="text-slate-500 mt-1">side effects only</p></div><div class="bg-rose-50 border border-rose-200 rounded-lg p-3 text-center"><p class="font-bold text-rose-700">input/output/model</p><p class="text-slate-500 mt-1">component API</p></div><div class="bg-purple-50 border border-purple-200 rounded-lg p-3 text-center"><p class="font-bold text-purple-700">resource() stable</p><p class="text-slate-500 mt-1">async data loading</p></div><div class="bg-cyan-50 border border-cyan-200 rounded-lg p-3 text-center"><p class="font-bold text-cyan-700">Enables zoneless</p><p class="text-slate-500 mt-1">no Zone.js needed</p></div></div></div>`
    },
    {
      "id": "what-are-signals",
      "title": "What are signals?",
      "explanation": `
        <div class="analogy-box">
          <svg class="analogy-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
          <div class="analogy-body">
            <p class="analogy-label">Think of it like</p>
            <p class="analogy-text">A <strong>spreadsheet cell holding a formula</strong> that recalculates itself the instant one of its inputs changes &mdash; nobody has to press F9 to refresh it. A <code>signal()</code> is the raw cell you type a number into. A <code>computed()</code> is the formula cell that watches other cells. Change <code>A1</code>, and every formula cell that references it updates on its own, in the right order, without you writing a single "refresh" line of code.</p>
          </div>
        </div>
        <p><strong>Signals</strong> are Angular's reactive primitive for managing state. A signal wraps a value and automatically tracks who reads it, notifying those readers when the value changes. Introduced in Angular 16 as developer preview and stable since Angular 17, signals are a fundamentally different reactivity model from the Zone.js + change detection approach Angular used since Angular 2 &mdash; and they're the reason zoneless apps work at all.</p>
        <p>The core idea: when you read a signal inside a template or a <code>computed()</code> call, Angular registers a dependency. When the signal's value changes, Angular knows exactly which templates and computed values need re-evaluating &mdash; and only those. No full component tree traversal, no Zone.js monkey-patching, no manual subscription bookkeeping.</p>
        <h3>Three signal primitives</h3>
        <p><code>signal(initialValue)</code> creates a writable signal &mdash; a piece of state you own. Read it by calling it as a function: <code>count()</code>. Update it with <code>.set()</code> or <code>.update()</code>.</p>
        <p><code>computed(() => expression)</code> creates a read-only derived signal, recalculated automatically whenever any signal it reads changes. It's lazy (only runs on first read) and memoized (returns the cached value if nothing it depends on has changed).</p>
        <p><code>effect(() => sideEffect)</code> runs a function whenever any signal it reads changes. Use it to synchronize with non-Angular systems &mdash; localStorage, analytics, third-party libraries &mdash; not to update Angular state (that belongs in a computed signal).</p>
        <div class="gotcha-box">
          <svg class="gotcha-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
          <div class="gotcha-body">
            <p class="gotcha-label">Common trap</p>
            <p class="gotcha-text"><code>.set()</code> and <code>.update()</code> are not interchangeable. <code>count.set(5)</code> replaces the value outright &mdash; call it with the *next* value, not a delta. <code>count.update(v =&gt; v + 1)</code> takes the *previous* value through a callback and returns the next one. Writing <code>count.set(count() + 1)</code> works but silently reads-then-writes non-atomically inside code that might run concurrently with other updates; writing <code>count.update(5)</code> instead of <code>count.set(5)</code> is a TypeScript error because <code>update()</code> expects a function, not a value. Mixing the two up is the single most common signals typo.</p>
          </div>
        </div>
      `,
      "code": "import { Component, signal, computed, effect } from '@angular/core';\n\n@Component({\n  selector: 'app-cart',\n  template: `\n    <h2>Cart ({{ itemCount() }} items)</h2>\n    <p>Subtotal: ${{ subtotal() }}</p>\n    <p>Tax (10%): ${{ tax() }}</p>\n    <p><strong>Total: ${{ total() }}</strong></p>\n\n    <button (click)=\"addItem()\">Add Item ($25)</button>\n    <button (click)=\"removeItem()\" [disabled]=\"items().length === 0\">Remove Item</button>\n  `\n})\nexport class CartComponent {\n  // Writable signal — this is the source of truth\n  items = signal<number[]>([]);\n\n  // Computed signals — automatically recalculate when items() changes\n  itemCount = computed(() => this.items().length);\n  subtotal  = computed(() => this.items().reduce((sum, p) => sum + p, 0));\n  tax       = computed(() => +(this.subtotal() * 0.1).toFixed(2));\n  total     = computed(() => +(this.subtotal() + this.tax()).toFixed(2));\n\n  constructor() {\n    // Effect: sync cart to localStorage whenever items change\n    effect(() => {\n      localStorage.setItem('cart', JSON.stringify(this.items()));\n      // Reading this.items() inside effect registers it as a dependency\n    });\n  }\n\n  addItem(): void {\n    // update() receives the PREVIOUS value and returns the NEXT value\n    this.items.update(current => [...current, 25]);\n  }\n\n  removeItem(): void {\n    this.items.update(current => current.slice(0, -1));\n  }\n}",
      "language": "typescript",
      "diagram": `<div class="diagram-wrap"><p class="text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5">Dependency Graph: signal &rarr; computed &rarr; effect</p><div class="flex flex-col items-center gap-2 text-xs"><div class="bg-indigo-50 border-2 border-indigo-200 rounded-lg px-4 py-2 text-center font-semibold text-indigo-700">signal(items) = [25, 25]</div><div class="text-slate-300">&darr;</div><div class="flex gap-3"><div class="bg-emerald-50 border-2 border-emerald-200 rounded-lg px-3 py-2 text-center font-semibold text-emerald-700">computed(subtotal)</div><div class="bg-emerald-50 border-2 border-emerald-200 rounded-lg px-3 py-2 text-center font-semibold text-emerald-700">computed(itemCount)</div></div><div class="text-slate-300">&darr;</div><div class="bg-amber-50 border-2 border-amber-200 rounded-lg px-4 py-2 text-center font-semibold text-amber-700">computed(total)</div><div class="text-slate-300">&darr;</div><div class="bg-rose-50 border-2 border-rose-200 rounded-lg px-4 py-2 text-center font-semibold text-rose-700">effect() → localStorage.setItem(...)</div></div></div>`
    },
    {
      "id": "signals-vs-observables",
      "title": "Difference between signals and observables",
      "explanation": `
        <div class="analogy-box">
          <svg class="analogy-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
          <div class="analogy-body">
            <p class="analogy-label">Think of it like</p>
            <p class="analogy-text">A <strong>water tank versus a river</strong>. A signal is the tank &mdash; dip a cup in at any moment and there's always a current water level to read, synchronously, no waiting. An Observable is the river &mdash; it might be flowing with values right now, might be completely dry, or might deliver exactly one bucket and then stop forever. You don't "check the level" of a river; you stand at the bank with a net and catch what flows past when it flows.</p>
          </div>
        </div>
        <p>Signals and Observables both handle reactivity in Angular, but they solve different problems with different mental models. Knowing when to reach for each is a core skill in modern Angular.</p>
        <h3>Signals — synchronous state</h3>
        <p>A signal always has a current value. Reading one (<code>count()</code>) gives you that value synchronously &mdash; no subscription, no async ceremony. Signals are built for <strong>local component state</strong> and derived values: a counter, a selected tab, a filter string, a computed subtotal. They integrate directly with Angular's template compiler, which reads them without needing the <code>async</code> pipe.</p>
        <h3>Observables — asynchronous event streams</h3>
        <p>An Observable represents a stream of values over time. It doesn't need a value right now &mdash; it might emit once, many times, or never. Observables are the right tool for <strong>HTTP requests</strong> (one response, then complete), <strong>WebSocket messages</strong> (many events), <strong>route parameter changes</strong> (a stream of URL changes), and <strong>form value changes</strong>. RxJS gives you a rich operator library for transforming, combining, and filtering those streams.</p>
        <h3>Complementary, not competing</h3>
        <p>The modern Angular pattern uses Observables at the application's <em>boundary</em> &mdash; HTTP, routing, form events &mdash; and converts them to signals inside components with <code>toSignal()</code>. That gives you the full power of RxJS operators for data fetching, and the simplicity of signals for template binding and derived state. It's also worth knowing why this matters beyond convenience: an app that reads state exclusively through signals can drop Zone.js entirely, because Angular knows precisely when a signal changed without needing to intercept every async browser API. That's the mechanism behind Angular 22's zoneless-by-default new apps.</p>
        <table class="w-full text-xs mt-3 border-collapse">
          <thead><tr class="bg-slate-100"><th class="p-2 text-left">Aspect</th><th class="p-2 text-left">Signal</th><th class="p-2 text-left">Observable</th></tr></thead>
          <tbody>
            <tr class="border-t"><td class="p-2">Always has a value</td><td class="p-2">Yes</td><td class="p-2">No (may not emit)</td></tr>
            <tr class="border-t"><td class="p-2">Reading style</td><td class="p-2">Call as function: <code>count()</code></td><td class="p-2">Subscribe or use async pipe</td></tr>
            <tr class="border-t"><td class="p-2">Template binding</td><td class="p-2">Direct — no pipe needed</td><td class="p-2">Requires <code>| async</code></td></tr>
            <tr class="border-t"><td class="p-2">Cleanup needed</td><td class="p-2">No (automatic)</td><td class="p-2">Yes (unsubscribe)</td></tr>
            <tr class="border-t"><td class="p-2">Best for</td><td class="p-2">Local state, derived values</td><td class="p-2">HTTP, streams, events</td></tr>
          </tbody>
        </table>
      `,
      "code": "import { Component, signal, computed, inject } from '@angular/core';\nimport { toSignal } from '@angular/core/rxjs-interop';\nimport { HttpClient } from '@angular/common/http';\nimport { switchMap } from 'rxjs/operators';\nimport { toObservable } from '@angular/core/rxjs-interop';\n\n@Component({\n  selector: 'app-user-detail',\n  template: `\n    <select (change)=\"userId.set(+$any($event.target).value)\">\n      <option value=\"1\">User 1</option>\n      <option value=\"2\">User 2</option>\n    </select>\n\n    <!-- No async pipe needed — user is a Signal, not an Observable -->\n    <div *ngIf=\"user()\">\n      <h2>{{ user()!.name }}</h2>\n      <p>{{ user()!.email }}</p>\n    </div>\n    <p *ngIf=\"!user()\">Loading...</p>\n  `\n})\nexport class UserDetailComponent {\n  private http = inject(HttpClient);\n\n  // Signal drives the selected user ID\n  userId = signal(1);\n\n  // Convert signal to Observable to use RxJS switchMap,\n  // then convert back to signal for the template\n  user = toSignal(\n    toObservable(this.userId).pipe(\n      switchMap(id => this.http.get<{ name: string; email: string }>(`/api/users/${id}`))\n    ),\n    { initialValue: null }\n  );\n\n  // Pure signal state — no Observable needed\n  isEditing = signal(false);\n  displayName = computed(() => this.user()?.name.toUpperCase() ?? 'Loading...');\n}",
      "language": "typescript",
      "diagram": `<div class="diagram-wrap"><p class="text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5">Two Worlds, One Bridge</p><div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs mb-4"><div class="bg-indigo-50 border border-indigo-200 rounded-lg p-3 text-center"><p class="font-bold text-indigo-700">Signal World</p><p class="text-slate-500 mt-1">component state, derived values</p></div><div class="bg-emerald-50 border border-emerald-200 rounded-lg p-3 text-center"><p class="font-bold text-emerald-700">Observable World</p><p class="text-slate-500 mt-1">HTTP, router, forms, WebSockets</p></div></div><div class="flex justify-center items-center gap-4 text-xs"><span class="bg-slate-800 text-white rounded px-3 py-1.5 font-mono">toSignal()</span><span class="text-slate-300">&harr;</span><span class="bg-slate-800 text-white rounded px-3 py-1.5 font-mono">toObservable()</span></div></div>`
    },
    {
      "id": "computed-signals",
      "title": "Computed signals",
      "explanation": `
        <div class="analogy-box">
          <svg class="analogy-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
          <div class="analogy-body">
            <p class="analogy-label">Think of it like</p>
            <p class="analogy-text">A <strong>quality-control scanner on a factory line</strong> that only re-scans a batch when the raw materials for that batch actually change. If the same batch rolls past again with nothing different about it, the scanner just reports its last result instead of re-running the whole inspection. That's memoization: <code>computed()</code> only redoes the work when a dependency has genuinely changed, and hands back the cached answer otherwise.</p>
          </div>
        </div>
        <p>A <strong>computed signal</strong> derives its value from one or more other signals. You define it with a pure function that reads signals and returns a derived value; Angular tracks exactly which signals the function read and re-runs it automatically whenever any of those change.</p>
        <p>The critical performance property is <strong>memoization</strong>. If a computed signal's dependencies haven't changed since the last read, Angular returns the cached value without re-running the function. That means you can define complex derived values &mdash; filtered lists, aggregated totals, formatted strings &mdash; freely, without worrying about recalculating them on every render.</p>
        <h3>Laziness</h3>
        <p>Computed signals are <em>lazy</em> &mdash; they don't calculate their value the moment they're created. The calculation runs the first time the computed signal is read, and again whenever a dependency changes and it's read again. If nothing ever reads a computed signal, its function never runs at all. This differs from RxJS pipes, which run whenever the source emits regardless of whether anyone is subscribed.</p>
        <h3>Read-only</h3>
        <p>Computed signals are read-only &mdash; there's no <code>.set()</code> on them. The only way to change a computed signal's value is to change one of its dependencies. This enforces single-direction data flow: writable signals are the state, computed signals are derived views of that state.</p>
        <div class="gotcha-box">
          <svg class="gotcha-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
          <div class="gotcha-body">
            <p class="gotcha-label">Common trap</p>
            <p class="gotcha-text"><code>computed()</code> must stay pure &mdash; no writing to other signals, no <code>console.log</code>-driven side effects you rely on, no API calls inside it. Because it's lazy and memoized, Angular may skip re-running it entirely if nothing reads it, or run it more than once during dependency tracking, so any side effect hidden inside a computed can run an unpredictable number of times or not at all. If you need a side effect, that's exactly what <code>effect()</code> is for.</p>
          </div>
        </div>
      `,
      "code": "import { Component, signal, computed } from '@angular/core';\n\ninterface Product {\n  id: number;\n  name: string;\n  price: number;\n  category: string;\n  inStock: boolean;\n}\n\n@Component({\n  selector: 'app-product-filter',\n  template: `\n    <input (input)=\"search.set($any($event.target).value)\" placeholder=\"Search...\" />\n    <select (change)=\"category.set($any($event.target).value)\">\n      <option value=\"\">All Categories</option>\n      <option value=\"electronics\">Electronics</option>\n      <option value=\"books\">Books</option>\n    </select>\n    <label>\n      <input type=\"checkbox\" (change)=\"inStockOnly.set($any($event.target).checked)\" />\n      In stock only\n    </label>\n\n    <!-- All computed — re-evaluates only when relevant signals change -->\n    <p>Showing {{ filteredCount() }} of {{ totalCount() }} products</p>\n    <p>Total value: ${{ filteredTotal() }}</p>\n\n    <div *ngFor=\"let p of filteredProducts()\">\n      {{ p.name }} — ${{ p.price }}\n    </div>\n  `\n})\nexport class ProductFilterComponent {\n  // Writable signals — the source of truth\n  products = signal<Product[]>([\n    { id: 1, name: 'Laptop',    price: 999, category: 'electronics', inStock: true  },\n    { id: 2, name: 'Headphones', price: 149, category: 'electronics', inStock: true  },\n    { id: 3, name: 'Clean Code', price: 35,  category: 'books',       inStock: false },\n    { id: 4, name: 'Webcam',    price: 89,  category: 'electronics', inStock: true  }\n  ]);\n  search     = signal('');\n  category   = signal('');\n  inStockOnly = signal(false);\n\n  // Computed signals — automatically re-evaluated when dependencies change\n  filteredProducts = computed(() => {\n    const s = this.search().toLowerCase();\n    return this.products().filter(p =>\n      (!s || p.name.toLowerCase().includes(s)) &&\n      (!this.category() || p.category === this.category()) &&\n      (!this.inStockOnly() || p.inStock)\n    );\n  });\n\n  totalCount    = computed(() => this.products().length);\n  filteredCount = computed(() => this.filteredProducts().length);\n  filteredTotal = computed(() =>\n    this.filteredProducts().reduce((sum, p) => sum + p.price, 0)\n  );\n}",
      "language": "typescript",
      "diagram": `<div class="diagram-wrap"><p class="text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5">Memoization: Same Inputs, No Recompute</p><div class="flex flex-col items-center gap-2 text-xs max-w-sm mx-auto"><div class="w-full bg-indigo-50 border border-indigo-200 rounded px-3 py-1.5 text-center">search() = "lap"</div><div class="text-slate-300">&darr;</div><div class="w-full bg-slate-800 text-white rounded px-3 py-1.5 text-center font-mono">filteredProducts() runs</div><div class="text-slate-300">&darr;</div><div class="w-full bg-emerald-50 border border-emerald-200 rounded px-3 py-1.5 text-center">read again, search() unchanged</div><div class="text-slate-300">&darr;</div><div class="w-full bg-amber-50 border border-amber-200 rounded px-3 py-1.5 text-center font-semibold text-amber-700">cached value returned — no recompute</div></div></div>`
    },
    {
      "id": "effect-function",
      "title": "Effect function",
      "explanation": `
        <div class="analogy-box">
          <svg class="analogy-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
          <div class="analogy-body">
            <p class="analogy-label">Think of it like</p>
            <p class="analogy-text">A <strong>smoke detector</strong>. It passively watches the air (reads signals) and reacts the instant it senses smoke (a dependency changes) by sounding an alarm (a side effect: writing to localStorage, calling an analytics API, updating a DOM attribute). What it does <em>not</em> do is put out the fire itself &mdash; it doesn't compute your app's state. If you need to derive a new value from other values, that's a job for <code>computed()</code>, not the alarm.</p>
          </div>
        </div>
        <p><code>effect()</code> runs a side-effect callback whenever any signal it reads changes. It's Angular's answer to "how do I react to signal changes outside a template?" &mdash; syncing state to external storage, logging, driving a third-party library, sending analytics events.</p>
        <p>The function passed to <code>effect()</code> runs immediately once on creation (to establish dependencies), then again whenever any signal it read during the last execution changes. Dependency tracking is dynamic &mdash; a signal read inside a conditional branch only becomes a dependency once that branch actually executes.</p>
        <h3>Injection context requirement</h3>
        <p><code>effect()</code> must be called within an injection context &mdash; typically the class constructor, or a function called during dependency injection. Effects are tied to the lifecycle of the injector that creates them: when the component is destroyed, its effects are automatically cleaned up. To create one outside the constructor (e.g., inside a callback), pass an <code>Injector</code> explicitly via the options object.</p>
        <h3>Cleaning up between runs</h3>
        <p>If an effect starts something that needs tearing down before the next run &mdash; a <code>setTimeout</code>, a manual event listener, a subscription to a non-Angular API &mdash; the callback receives an <code>onCleanup</code> function as its argument. Register a cleanup callback with it, and Angular calls it right before the effect re-runs, and again when the effect itself is destroyed. Skipping this is how effects leak timers and listeners.</p>
        <div class="gotcha-box">
          <svg class="gotcha-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
          <div class="gotcha-body">
            <p class="gotcha-label">Common trap</p>
            <p class="gotcha-text">Dependency tracking only sees signals read <em>synchronously</em> during the effect body's execution. A signal read inside a <code>setTimeout</code> callback, a <code>.then()</code>, or a branch that didn't run this time is invisible to the tracker &mdash; the effect silently stops reacting to it. And updating a signal inside an effect that also reads that same signal creates an infinite loop (the write triggers the effect, which writes again); Angular throws in development mode to catch this, but the fix is always the same: move derivations into <code>computed()</code> and keep <code>effect()</code> strictly for one-way side effects.</p>
          </div>
        </div>
      `,
      "code": "import { Component, signal, effect, OnInit, inject, Injector } from '@angular/core';\n\n@Component({\n  selector: 'app-settings',\n  template: `\n    <label>Theme:\n      <select (change)=\"theme.set($any($event.target).value)\">\n        <option value=\"light\">Light</option>\n        <option value=\"dark\">Dark</option>\n        <option value=\"system\">System</option>\n      </select>\n    </label>\n    <label>Font size: {{ fontSize() }}px\n      <input type=\"range\" min=\"12\" max=\"24\"\n        [value]=\"fontSize()\"\n        (input)=\"fontSize.set(+$any($event.target).value)\" />\n    </label>\n  `\n})\nexport class SettingsComponent {\n  // Load saved settings from localStorage\n  theme    = signal<string>(localStorage.getItem('theme') ?? 'system');\n  fontSize = signal<number>(+(localStorage.getItem('fontSize') ?? '16'));\n\n  constructor() {\n    // Effect 1: sync theme to localStorage and DOM\n    effect(() => {\n      const t = this.theme();\n      localStorage.setItem('theme', t);\n      document.documentElement.setAttribute('data-theme', t);\n      // Both signals read — effect re-runs if either changes\n    });\n\n    // Effect 2: debounced save with cleanup — cancels the pending timer\n    // if fontSize changes again before the timeout fires\n    effect((onCleanup) => {\n      const size = fontSize();\n      const timer = setTimeout(() => {\n        localStorage.setItem('fontSize', String(size));\n      }, 300);\n      onCleanup(() => clearTimeout(timer));\n    });\n  }\n}\n\n// ---- Creating an effect outside the constructor ----\n@Component({ selector: 'app-dynamic', template: '' })\nexport class DynamicComponent {\n  private injector = inject(Injector);\n  count = signal(0);\n\n  startTracking(): void {\n    // Pass injector explicitly when creating effects outside constructor\n    effect(() => {\n      console.log('Count changed:', this.count());\n    }, { injector: this.injector });\n  }\n}",
      "language": "typescript",
      "diagram": `<div class="diagram-wrap"><p class="text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5">Effect Lifecycle</p><div class="flex flex-wrap items-center justify-center gap-2 text-xs"><div class="bg-indigo-50 border-2 border-indigo-200 rounded-lg px-3 py-2 text-center font-semibold text-indigo-700">Created<br><span class="font-normal text-slate-500">runs once</span></div><span class="text-slate-300">&rarr;</span><div class="bg-emerald-50 border-2 border-emerald-200 rounded-lg px-3 py-2 text-center font-semibold text-emerald-700">Dependency changes</div><span class="text-slate-300">&rarr;</span><div class="bg-amber-50 border-2 border-amber-200 rounded-lg px-3 py-2 text-center font-semibold text-amber-700">onCleanup() runs</div><span class="text-slate-300">&rarr;</span><div class="bg-rose-50 border-2 border-rose-200 rounded-lg px-3 py-2 text-center font-semibold text-rose-700">Effect re-runs</div><span class="text-slate-300">&rarr;</span><div class="bg-purple-50 border-2 border-purple-200 rounded-lg px-3 py-2 text-center font-semibold text-purple-700">Component destroyed<br><span class="font-normal text-slate-500">final cleanup</span></div></div></div>`
    },
    {
      "id": "signal-based-components",
      "title": "Signal-based inputs, outputs and model",
      "explanation": `
        <div class="analogy-box">
          <svg class="analogy-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
          <div class="analogy-body">
            <p class="analogy-label">Think of it like</p>
            <p class="analogy-text">A household intercom system. <code>input()</code> is a one-way speaker in the child's room &mdash; the parent talks, the child only listens. <code>output()</code> is a one-way call button the child presses to summon the parent &mdash; the child speaks, the parent listens. <code>model()</code> is a walkie-talkie: either side can talk, and both sides hear updates the moment the other one speaks.</p>
          </div>
        </div>
        <p>Angular 17+ introduced signal-based alternatives to <code>@Input()</code>, <code>@Output()</code>, and two-way binding. They wire component communication directly into the signal system, making the whole data flow &mdash; parent to child, child to parent, and back &mdash; reactive without Zone.js.</p>
        <h3>input() — signal inputs</h3>
        <p>Instead of <code>@Input() productId!: number</code>, write <code>productId = input.required&lt;number&gt;()</code>. The result is a read-only signal, read inside the component as <code>this.productId()</code>. It participates in <code>computed()</code> and <code>effect()</code> automatically &mdash; you can derive a computed value from an input signal without <code>ngOnChanges</code>. <code>input.required()</code> enforces the parent must provide the value, just like <code>@Input({ required: true })</code> did.</p>
        <h3>output() — signal outputs</h3>
        <p>Instead of <code>@Output() selected = new EventEmitter&lt;Product&gt;()</code>, write <code>selected = output&lt;Product&gt;()</code>. Emit with <code>this.selected.emit(product)</code>. The parent template binds the same way it always did: <code>(selected)="onSelect($event)"</code>. Signal outputs are simpler because they don't extend <code>Subject</code> &mdash; pure event emitters, no Observable overhead.</p>
        <h3>model() — two-way binding signal</h3>
        <p><code>model()</code> creates a writable signal that's also an input/output pair. The child reads and writes it like a regular signal. The parent binds with <code>[(value)]="parentProp"</code> &mdash; the same two-way binding syntax <code>ngModel</code> used. When the child calls <code>this.value.set(newValue)</code>, the change propagates back to the parent automatically.</p>
      `,
      "code": "import { Component, input, output, model, computed } from '@angular/core';\n\ninterface Product { id: number; name: string; price: number; }\n\n// ---- Child component using signal-based API ----\n@Component({\n  selector: 'app-product-card',\n  template: `\n    <div class=\"card\">\n      <h3>{{ product().name }}</h3>\n      <p>${{ product().price }}</p>\n      <p>Qty: {{ quantity() }}</p>\n      <button (click)=\"quantity.set(quantity() + 1)\">+</button>\n      <button (click)=\"quantity.set(Math.max(1, quantity() - 1))\">-</button>\n      <button (click)=\"addToCart()\">Add to Cart</button>\n    </div>\n  `\n})\nexport class ProductCardComponent {\n  // input() — read-only signal, required from parent\n  product = input.required<Product>();\n\n  // input() with default — optional\n  maxQuantity = input<number>(10);\n\n  // model() — two-way binding: parent can read AND write this\n  quantity = model<number>(1);\n\n  // output() — pure event emitter\n  cartAdded = output<{ product: Product; quantity: number }>();\n\n  // Computed from input signal — reacts automatically when product changes\n  discountedPrice = computed(() => this.product().price * 0.9);\n\n  Math = Math; // expose to template\n\n  addToCart(): void {\n    this.cartAdded.emit({ product: this.product(), quantity: this.quantity() });\n    this.quantity.set(1); // reset\n  }\n}\n\n// ---- Parent using all three ----\n@Component({\n  selector: 'app-shop',\n  imports: [ProductCardComponent],\n  template: `\n    <app-product-card\n      [product]=\"featuredProduct\"\n      [(quantity)]=\"selectedQty\"\n      (cartAdded)=\"handleCartAdd($event)\"\n    ></app-product-card>\n    <p>Selected quantity in parent: {{ selectedQty }}</p>\n  `\n})\nexport class ShopComponent {\n  featuredProduct: Product = { id: 1, name: 'Laptop', price: 999 };\n  selectedQty = 1;\n\n  handleCartAdd(event: { product: Product; quantity: number }): void {\n    console.log(`Added ${event.quantity}x ${event.product.name} to cart`);\n  }\n}",
      "language": "typescript",
      "diagram": `<div class="diagram-wrap"><p class="text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5">input / output / model — Data Direction</p><div class="flex flex-col items-center gap-3 max-w-xs mx-auto text-xs"><div class="bg-slate-800 text-white rounded-lg px-3 py-1.5 w-full text-center">Parent Component</div><div class="flex flex-col gap-1 w-full"><div class="flex items-center gap-2"><span class="text-indigo-500 w-4">&darr;</span><span class="bg-indigo-50 border border-indigo-200 rounded px-2 py-1 flex-1 text-center text-indigo-700">input() — one-way down</span></div><div class="flex items-center gap-2"><span class="text-emerald-500 w-4">&uarr;</span><span class="bg-emerald-50 border border-emerald-200 rounded px-2 py-1 flex-1 text-center text-emerald-700">output() — one-way up</span></div><div class="flex items-center gap-2"><span class="text-amber-500 w-4">&harr;</span><span class="bg-amber-50 border border-amber-200 rounded px-2 py-1 flex-1 text-center text-amber-700">model() — two-way</span></div></div><div class="bg-slate-100 border border-slate-300 rounded-lg px-3 py-1.5 w-full text-center text-slate-600">Child Component</div></div></div>`
    },
    {
      "id": "advanced-signal-apis",
      "title": "Advanced Signal APIs: toSignal, toObservable, linkedSignal, resource",
      "explanation": `
        <div class="analogy-box">
          <svg class="analogy-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
          <div class="analogy-body">
            <p class="analogy-label">Think of it like</p>
            <p class="analogy-text"><code>linkedSignal()</code> is a whiteboard running total that a manager erases and rewrites fresh every time the underlying order list changes &mdash; but between resets, an employee can also scribble a correction directly on the board. <code>resource()</code> is a delivery tracking kiosk: punch in a request, and the board automatically shows "preparing," "ready," or "failed, try again" without you polling it yourself.</p>
          </div>
        </div>
        <p>Angular ships several utilities that bridge the signal and Observable worlds, making it practical to adopt signals incrementally in existing Observable-heavy codebases &mdash; and, as of Angular 22, to build async data loading entirely out of stable signal primitives.</p>
        <h3>toSignal() — Observable to signal</h3>
        <p><code>toSignal(observable$)</code> subscribes to an Observable and returns a signal holding the latest emitted value, automatically unsubscribing when the component is destroyed. The <code>initialValue</code> option sets the value before the first emission. Use this to convert HTTP responses, route params, and form value streams into signals your templates can read directly, no <code>| async</code> needed.</p>
        <h3>toObservable() — signal to Observable</h3>
        <p><code>toObservable(signal)</code> converts a signal into an Observable that emits whenever the signal changes. Reach for this when you need RxJS operators like <code>switchMap</code>, <code>debounceTime</code>, or <code>distinctUntilChanged</code> applied to signal changes &mdash; for example, triggering a debounced API call when a search signal changes.</p>
        <h3>linkedSignal() — resettable derived signal</h3>
        <p><code>linkedSignal()</code> creates a writable signal whose value resets based on a source signal. Unlike <code>computed()</code> (always read-only), a <code>linkedSignal</code> can be written to locally but reverts to the derived value whenever the source changes. The classic use case: a selection or pagination cursor that should reset when the list it operates on changes.</p>
        <h3>resource() — async data with loading/error state, now stable</h3>
        <p><code>resource()</code> manages asynchronous data fetching declaratively. You provide a <code>request</code> signal and a <code>loader</code> function; whenever the request changes, the loader runs automatically. The result exposes <code>.value()</code>, <code>.isLoading()</code>, and <code>.error()</code> signals, replacing the boilerplate of a BehaviorSubject plus switchMap plus manual loading flag. <code>resource()</code>, <code>rxResource()</code> (for RxJS-based loaders), and <code>httpResource()</code> (a thin, purpose-built wrapper over HttpClient) all graduated to stable in Angular 22 &mdash; no more experimental warnings, safe to use in production.</p>
        <div class="gotcha-box">
          <svg class="gotcha-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
          <div class="gotcha-body">
            <p class="gotcha-label">Common trap</p>
            <p class="gotcha-text">A <code>linkedSignal()</code>'s source must be read <em>inside</em> the computation callback for dependency tracking to see it &mdash; the same rule <code>computed()</code> follows. Reading the source signal outside the callback and closing over a stale variable means the linked signal never resets when you expect it to, and the bug only shows up as "my page number didn't reset after I changed the filter," which is easy to misdiagnose as a state management issue elsewhere.</p>
          </div>
        </div>
      `,
      "code": "import { Component, signal, computed, linkedSignal, resource, inject } from '@angular/core';\nimport { toSignal, toObservable } from '@angular/core/rxjs-interop';\nimport { HttpClient } from '@angular/common/http';\nimport { switchMap, debounceTime, distinctUntilChanged } from 'rxjs/operators';\n\n@Component({\n  selector: 'app-product-search',\n  template: `\n    <input (input)=\"query.set($any($event.target).value)\" placeholder=\"Search...\" />\n\n    @if (results.isLoading()) {\n      <p>Searching...</p>\n    } @else if (results.error()) {\n      <p>Error: {{ results.error() }}</p>\n    } @else {\n      <p>Found {{ results.value()?.length ?? 0 }} products</p>\n      <div *ngFor=\"let p of results.value()\">\n        <strong (click)=\"selectedCategory.set(p.category)\">{{ p.name }}</strong>\n      </div>\n    }\n\n    <!-- linkedSignal: resets page to 1 whenever query changes -->\n    <p>Page {{ page() }}</p>\n    <button (click)=\"page.set(page() + 1)\">Next</button>\n  `\n})\nexport class ProductSearchComponent {\n  private http = inject(HttpClient);\n\n  query = signal('');\n  selectedCategory = signal<string | null>(null);\n\n  // linkedSignal: page resets to 1 whenever query changes,\n  // but can also be set directly (e.g., by Next button).\n  // The source signal MUST be read inside this callback to be tracked.\n  page = linkedSignal(() => {\n    this.query(); // dependency: reset when query changes\n    return 1;\n  });\n\n  // resource: stable in Angular 22 — manages async fetch with\n  // automatic loading/error states, no hand-rolled flags\n  results = resource({\n    // Re-fetches whenever query or page changes\n    request: () => ({ q: this.query(), p: this.page() }),\n    loader: ({ request }) =>\n      this.http.get<any[]>(`/api/products?q=${request.q}&page=${request.p}`)\n        .toPromise()\n  });\n\n  // toSignal + toObservable: debounce query changes before fetching\n  debouncedQuery = toSignal(\n    toObservable(this.query).pipe(\n      debounceTime(300),\n      distinctUntilChanged()\n    ),\n    { initialValue: '' }\n  );\n}",
      "language": "typescript",
      "diagram": `<div class="diagram-wrap"><p class="text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5">resource() — Three States, One Signal Bundle</p><div class="flex flex-wrap items-center justify-center gap-2 text-xs"><div class="bg-indigo-50 border-2 border-indigo-200 rounded-lg px-3 py-2 text-center font-semibold text-indigo-700">request signal changes</div><span class="text-slate-300">&rarr;</span><div class="bg-amber-50 border-2 border-amber-200 rounded-lg px-3 py-2 text-center font-semibold text-amber-700">isLoading() = true</div><span class="text-slate-300">&rarr;</span><div class="flex gap-2"><div class="bg-emerald-50 border-2 border-emerald-200 rounded-lg px-3 py-2 text-center font-semibold text-emerald-700">value() set</div><div class="bg-rose-50 border-2 border-rose-200 rounded-lg px-3 py-2 text-center font-semibold text-rose-700">error() set</div></div></div></div>`
    },
    {
      "id": "migration-from-observable-pattern",
      "title": "Migrating from Observable to Signal pattern",
      "explanation": `
        <div class="analogy-box">
          <svg class="analogy-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
          <div class="analogy-body">
            <p class="analogy-label">Think of it like</p>
            <p class="analogy-text">Renovating a house <strong>one room at a time while you keep living in it</strong>. You don't tear out the plumbing (Observables at the HTTP/router/forms boundary, which are genuinely good at streaming async events) &mdash; you renovate the living room (local component state) into something simpler, and build a hallway (<code>toSignal()</code>/<code>toObservable()</code>) connecting the old plumbing to the new room. Nobody has to move out during the work.</p>
          </div>
        </div>
        <p>Signals and Observables coexist happily in the same application. Angular's migration path is deliberately incremental &mdash; you don't rewrite everything at once. The bridging utilities <code>toSignal()</code> and <code>toObservable()</code> let you move the boundary between the two worlds wherever makes sense for your codebase, one component at a time.</p>
        <h3>What changes, what stays the same</h3>
        <p>Keep Observables for data sources: HTTP calls, WebSockets, route params, form value changes. These are inherently asynchronous event streams, and RxJS operators handle them elegantly. Convert to signals at the component level with <code>toSignal()</code>. Replace local component state (a <code>BehaviorSubject</code> used only within a component) with a writable signal. Replace <code>combineLatest</code> + <code>map</code> chains for derived UI values with <code>computed()</code>.</p>
        <h3>Template simplification</h3>
        <p>The most visible change when migrating is template simplification. With Observables, every async value needs <code>| async</code> and an <code>*ngIf="data$ | async as data"</code> wrapper to avoid null checks. With signals, you read the value directly: <code>{{ user()?.name }}</code>. No async pipe, no nesting.</p>
        <h3>The new control flow syntax</h3>
        <p>Angular's built-in control flow blocks (<code>@if</code>, <code>@for</code>, <code>@switch</code>) work naturally with signals. Combined with signal-based inputs, they remove the need for <code>NgIf</code>, <code>NgFor</code>, and <code>NgSwitch</code> imports in standalone components, and make loading/error/data state patterns clean and readable.</p>
      `,
      "code": "import { Component, signal, computed, inject } from '@angular/core';\nimport { toSignal } from '@angular/core/rxjs-interop';\nimport { HttpClient } from '@angular/common/http';\nimport { switchMap, catchError, of } from 'rxjs';\nimport { toObservable } from '@angular/core/rxjs-interop';\n\n// ---- BEFORE: Observable-heavy pattern ----\n// @Component({\n//   template: `\n//     <ng-container *ngIf=\"filteredItems$ | async as items\">\n//       <li *ngFor=\"let item of items\">{{ item.name }}</li>\n//     </ng-container>\n//   `\n// })\n// export class OldComponent {\n//   filter$ = new BehaviorSubject('');\n//   items$ = this.http.get<Item[]>('/api/items');\n//   filteredItems$ = combineLatest([this.items$, this.filter$]).pipe(\n//     map(([items, filter]) => items.filter(i => i.name.includes(filter)))\n//   );\n// }\n\n// ---- AFTER: Signal-first pattern ----\n@Component({\n  selector: 'app-item-list',\n  template: `\n    <input (input)=\"filter.set($any($event.target).value)\" placeholder=\"Filter...\" />\n\n    @if (isLoading()) {\n      <p>Loading items...</p>\n    } @else if (error()) {\n      <p>Failed to load: {{ error() }}</p>\n    } @else {\n      @for (item of filteredItems(); track item.id) {\n        <li>{{ item.name }}</li>\n      } @empty {\n        <li>No items match your filter.</li>\n      }\n    }\n  `\n})\nexport class NewComponent {\n  private http = inject(HttpClient);\n\n  // Local state as writable signals\n  filter    = signal('');\n  isLoading = signal(true);\n  error     = signal<string | null>(null);\n\n  // Convert HTTP Observable to signal\n  items = toSignal(\n    this.http.get<{ id: number; name: string }[]>('/api/items').pipe(\n      catchError(err => {\n        this.error.set(err.message);\n        return of([]);\n      })\n    ),\n    {\n      initialValue: [],\n      // Called synchronously — marks loading complete\n      rejectErrors: false\n    }\n  );\n\n  // Derived state as computed — no RxJS needed\n  filteredItems = computed(() => {\n    this.isLoading.set(false); // mark loaded once items signal has a value\n    return this.items().filter(i =>\n      i.name.toLowerCase().includes(this.filter().toLowerCase())\n    );\n  });\n}",
      "language": "typescript",
      "diagram": `<div class="diagram-wrap"><p class="text-center text-xs font-bold text-slate-400 uppercase tracking-widest mb-5">Migration Boundary</p><div class="grid grid-cols-1 md:grid-cols-3 gap-2 items-center text-xs"><div class="bg-emerald-50 border border-emerald-200 rounded-lg p-3 text-center"><p class="font-bold text-emerald-700">Keep as Observables</p><p class="text-slate-500 mt-1">HTTP, router, forms, WebSockets</p></div><div class="flex md:flex-col items-center justify-center gap-1"><span class="text-slate-300 text-lg">&rarr;</span><span class="bg-slate-800 text-white rounded px-2 py-1 font-mono text-[10px]">toSignal()</span></div><div class="bg-indigo-50 border border-indigo-200 rounded-lg p-3 text-center"><p class="font-bold text-indigo-700">Convert to Signals</p><p class="text-slate-500 mt-1">component state, templates</p></div></div></div>`
    }
  ]
});
