window.MODULES = window.MODULES || [];
window.MODULES.push({
  "id": "signals",
  "title": "Signals (Angular 16+)",
  "icon": "bi bi-reception-4",
  "questions": [
    {
      "id": "what-are-signals",
      "title": "What are signals?",
      "explanation": "\n          <p><strong>Signals</strong> are Angular's reactive primitive for managing state. A signal is a wrapper around a value that automatically tracks who reads it and notifies those consumers when the value changes. Introduced in Angular 16 as developer preview and stabilized in Angular 17, signals represent a fundamentally different model of reactivity from the Zone.js + change detection approach Angular has used since Angular 2.</p>\n\n          <p>The core idea is simple: when you read a signal inside a template or a <code>computed()</code> call, Angular registers a dependency. When the signal's value changes, Angular knows exactly which templates and computed values need to be re-evaluated — and only those. No full component tree traversal, no Zone.js monkey-patching, no manual subscription management.</p>\n\n          <h3>Three Signal Primitives</h3>\n          <p><code>signal(initialValue)</code> creates a writable signal — a piece of state you control. You read it by calling it as a function: <code>count()</code>. You update it with <code>.set()</code> or <code>.update()</code>.</p>\n          <p><code>computed(() => expression)</code> creates a read-only derived signal whose value is automatically recalculated whenever any signal it reads changes. It is lazy (only calculates on first read) and memoized (returns the cached value if dependencies have not changed).</p>\n          <p><code>effect(() => sideEffect)</code> runs a function whenever any signal it reads changes. Use this for synchronizing to non-Angular systems — localStorage, analytics, third-party libraries — not for updating Angular state (that belongs in computed signals).</p>\n        ",
      "code": "import { Component, signal, computed, effect } from '@angular/core';\n\n@Component({\n  selector: 'app-cart',\n  standalone: true,\n  template: `\n    <h2>Cart ({{ itemCount() }} items)</h2>\n    <p>Subtotal: ${{ subtotal() }}</p>\n    <p>Tax (10%): ${{ tax() }}</p>\n    <p><strong>Total: ${{ total() }}</strong></p>\n\n    <button (click)=\"addItem()\">Add Item ($25)</button>\n    <button (click)=\"removeItem()\" [disabled]=\"items().length === 0\">Remove Item</button>\n  `\n})\nexport class CartComponent {\n  // Writable signal — this is the source of truth\n  items = signal<number[]>([]);\n\n  // Computed signals — automatically recalculate when items() changes\n  itemCount = computed(() => this.items().length);\n  subtotal  = computed(() => this.items().reduce((sum, p) => sum + p, 0));\n  tax       = computed(() => +(this.subtotal() * 0.1).toFixed(2));\n  total     = computed(() => +(this.subtotal() + this.tax()).toFixed(2));\n\n  constructor() {\n    // Effect: sync cart to localStorage whenever items change\n    effect(() => {\n      localStorage.setItem('cart', JSON.stringify(this.items()));\n      // Reading this.items() inside effect registers it as a dependency\n    });\n  }\n\n  addItem(): void {\n    this.items.update(current => [...current, 25]);\n  }\n\n  removeItem(): void {\n    this.items.update(current => current.slice(0, -1));\n  }\n}",
      "language": "typescript"
    },
    {
      "id": "signals-vs-observables",
      "title": "Difference between signals and observables",
      "explanation": "\n          <p>Signals and Observables both handle reactivity in Angular, but they address different problems and have different mental models. Understanding when to use each is a key skill for modern Angular development.</p>\n\n          <h3>Signals — Synchronous State</h3>\n          <p>A signal always has a current value. Reading a signal (<code>count()</code>) gives you the current value synchronously — no subscription, no async ceremony. Signals are designed for <strong>local component state</strong> and derived values: a counter, a selected tab, a filter string, a computed subtotal. They integrate directly with Angular's template compiler, which can read them without the <code>async</code> pipe.</p>\n\n          <h3>Observables — Asynchronous Event Streams</h3>\n          <p>An Observable represents a stream of values over time. It does not need to have a value right now — it might emit one value, many values, or never emit at all. Observables are the right tool for <strong>HTTP requests</strong> (one response, then complete), <strong>WebSocket messages</strong> (many events), <strong>route parameter changes</strong> (stream of URL changes), and <strong>form value changes</strong>. They come with a rich operator library (RxJS) for transforming, combining, and filtering streams.</p>\n\n          <h3>They Are Complementary, Not Competing</h3>\n          <p>The modern Angular pattern is to use Observables at the <em>boundary</em> of the application (HTTP, routing, form events) and convert them to signals inside components using <code>toSignal()</code>. This gives you the full power of RxJS operators for data fetching and the simplicity of signals for template binding and derived state.</p>\n\n          <table class=\"w-full text-xs mt-3 border-collapse\">\n            <thead><tr class=\"bg-slate-100\"><th class=\"p-2 text-left\">Aspect</th><th class=\"p-2 text-left\">Signal</th><th class=\"p-2 text-left\">Observable</th></tr></thead>\n            <tbody>\n              <tr class=\"border-t\"><td class=\"p-2\">Always has a value</td><td class=\"p-2\">Yes</td><td class=\"p-2\">No (may not emit)</td></tr>\n              <tr class=\"border-t\"><td class=\"p-2\">Reading style</td><td class=\"p-2\">Call as function: <code>count()</code></td><td class=\"p-2\">Subscribe or use async pipe</td></tr>\n              <tr class=\"border-t\"><td class=\"p-2\">Template binding</td><td class=\"p-2\">Direct — no pipe needed</td><td class=\"p-2\">Requires <code>| async</code></td></tr>\n              <tr class=\"border-t\"><td class=\"p-2\">Cleanup needed</td><td class=\"p-2\">No (automatic)</td><td class=\"p-2\">Yes (unsubscribe)</td></tr>\n              <tr class=\"border-t\"><td class=\"p-2\">Best for</td><td class=\"p-2\">Local state, derived values</td><td class=\"p-2\">HTTP, streams, events</td></tr>\n            </tbody>\n          </table>\n        ",
      "code": "import { Component, signal, computed, inject } from '@angular/core';\nimport { toSignal } from '@angular/core/rxjs-interop';\nimport { HttpClient } from '@angular/common/http';\nimport { switchMap } from 'rxjs/operators';\nimport { toObservable } from '@angular/core/rxjs-interop';\n\n@Component({\n  selector: 'app-user-detail',\n  standalone: true,\n  template: `\n    <select (change)=\"userId.set(+$any($event.target).value)\">\n      <option value=\"1\">User 1</option>\n      <option value=\"2\">User 2</option>\n    </select>\n\n    <!-- No async pipe needed — user is a Signal, not an Observable -->\n    <div *ngIf=\"user()\">\n      <h2>{{ user()!.name }}</h2>\n      <p>{{ user()!.email }}</p>\n    </div>\n    <p *ngIf=\"!user()\">Loading...</p>\n  `\n})\nexport class UserDetailComponent {\n  private http = inject(HttpClient);\n\n  // Signal drives the selected user ID\n  userId = signal(1);\n\n  // Convert signal to Observable to use RxJS switchMap,\n  // then convert back to signal for the template\n  user = toSignal(\n    toObservable(this.userId).pipe(\n      switchMap(id => this.http.get<{ name: string; email: string }>(`/api/users/${id}`))\n    ),\n    { initialValue: null }\n  );\n\n  // Pure signal state — no Observable needed\n  isEditing = signal(false);\n  displayName = computed(() => this.user()?.name.toUpperCase() ?? 'Loading...');\n}",
      "language": "typescript"
    },
    {
      "id": "computed-signals",
      "title": "Computed signals",
      "explanation": "\n          <p>A <strong>computed signal</strong> derives its value from one or more other signals. You define it with a pure function that reads signals and returns a derived value. Angular tracks which signals the function reads and automatically re-runs the function whenever any of those dependencies change.</p>\n\n          <p>The critical performance property of computed signals is <strong>memoization</strong>. If a computed signal's dependencies have not changed since the last read, Angular returns the cached value without re-running the function. This means you can freely define complex derived values — filtered lists, aggregated totals, formatted strings — without worrying about performance from excessive recalculation.</p>\n\n          <h3>Laziness</h3>\n          <p>Computed signals are <em>lazy</em> — they do not calculate their value when created. The calculation runs the first time the computed signal is read, and again whenever a dependency changes and the computed signal is read again. If no one reads a computed signal, it never runs. This is different from RxJS pipes, which run whenever the source emits regardless of whether anything is subscribed.</p>\n\n          <h3>Read-Only</h3>\n          <p>Computed signals are read-only. You cannot call <code>.set()</code> on them. The only way to change a computed signal's value is to change one of its dependencies. This enforces the single-direction data flow: writable signals are the state, computed signals are derived views of that state.</p>\n        ",
      "code": "import { Component, signal, computed } from '@angular/core';\n\ninterface Product {\n  id: number;\n  name: string;\n  price: number;\n  category: string;\n  inStock: boolean;\n}\n\n@Component({\n  selector: 'app-product-filter',\n  standalone: true,\n  template: `\n    <input (input)=\"search.set($any($event.target).value)\" placeholder=\"Search...\" />\n    <select (change)=\"category.set($any($event.target).value)\">\n      <option value=\"\">All Categories</option>\n      <option value=\"electronics\">Electronics</option>\n      <option value=\"books\">Books</option>\n    </select>\n    <label>\n      <input type=\"checkbox\" (change)=\"inStockOnly.set($any($event.target).checked)\" />\n      In stock only\n    </label>\n\n    <!-- All computed — re-evaluates only when relevant signals change -->\n    <p>Showing {{ filteredCount() }} of {{ totalCount() }} products</p>\n    <p>Total value: ${{ filteredTotal() }}</p>\n\n    <div *ngFor=\"let p of filteredProducts()\">\n      {{ p.name }} — ${{ p.price }}\n    </div>\n  `\n})\nexport class ProductFilterComponent {\n  // Writable signals — the source of truth\n  products = signal<Product[]>([\n    { id: 1, name: 'Laptop',    price: 999, category: 'electronics', inStock: true  },\n    { id: 2, name: 'Headphones', price: 149, category: 'electronics', inStock: true  },\n    { id: 3, name: 'Clean Code', price: 35,  category: 'books',       inStock: false },\n    { id: 4, name: 'Webcam',    price: 89,  category: 'electronics', inStock: true  }\n  ]);\n  search     = signal('');\n  category   = signal('');\n  inStockOnly = signal(false);\n\n  // Computed signals — automatically re-evaluated when dependencies change\n  filteredProducts = computed(() => {\n    const s = this.search().toLowerCase();\n    return this.products().filter(p =>\n      (!s || p.name.toLowerCase().includes(s)) &&\n      (!this.category() || p.category === this.category()) &&\n      (!this.inStockOnly() || p.inStock)\n    );\n  });\n\n  totalCount    = computed(() => this.products().length);\n  filteredCount = computed(() => this.filteredProducts().length);\n  filteredTotal = computed(() =>\n    this.filteredProducts().reduce((sum, p) => sum + p.price, 0)\n  );\n}",
      "language": "typescript"
    },
    {
      "id": "effect-function",
      "title": "Effect function",
      "explanation": "\n          <p>The <code>effect()</code> function runs a side-effect callback whenever any signal it reads changes. It is Angular's answer to the question: \"How do I react to signal changes outside of the template?\" — for tasks like syncing state to external storage, logging, updating a third-party library, or sending analytics events.</p>\n\n          <p>The function you pass to <code>effect()</code> is called immediately once on creation (to establish dependencies), and then again whenever any signal it read during the last execution changes. Angular tracks dependencies dynamically — if a signal is read inside a conditional branch, it only becomes a dependency when that branch executes.</p>\n\n          <h3>Injection Context Requirement</h3>\n          <p><code>effect()</code> must be called within an injection context — typically the class constructor, or a function called during dependency injection. This is because effects are tied to the lifecycle of the injector that creates them: when the component is destroyed, its effects are automatically cleaned up. If you need to create an effect outside the constructor (e.g., in a callback), pass an injector explicitly via the options object.</p>\n\n          <h3>Do Not Update Signals Inside effects</h3>\n          <p>Updating a signal inside an effect that also reads that signal creates an infinite loop. The effect runs, updates the signal, which triggers the effect again. Angular throws an error in development mode to catch this pattern. To derive a value from signals, use <code>computed()</code>. Effects are for communicating with the outside world, not for computing state.</p>\n        ",
      "code": "import { Component, signal, effect, OnInit, inject, Injector } from '@angular/core';\n\n@Component({\n  selector: 'app-settings',\n  standalone: true,\n  template: `\n    <label>Theme:\n      <select (change)=\"theme.set($any($event.target).value)\">\n        <option value=\"light\">Light</option>\n        <option value=\"dark\">Dark</option>\n        <option value=\"system\">System</option>\n      </select>\n    </label>\n    <label>Font size: {{ fontSize() }}px\n      <input type=\"range\" min=\"12\" max=\"24\"\n        [value]=\"fontSize()\"\n        (input)=\"fontSize.set(+$any($event.target).value)\" />\n    </label>\n  `\n})\nexport class SettingsComponent {\n  // Load saved settings from localStorage\n  theme    = signal<string>(localStorage.getItem('theme') ?? 'system');\n  fontSize = signal<number>(+(localStorage.getItem('fontSize') ?? '16'));\n\n  constructor() {\n    // Effect 1: sync theme to localStorage and DOM\n    effect(() => {\n      const t = this.theme();\n      localStorage.setItem('theme', t);\n      document.documentElement.setAttribute('data-theme', t);\n      // Both signals read — effect re-runs if either changes\n    });\n\n    // Effect 2: sync font size to localStorage and CSS variable\n    effect(() => {\n      const size = this.fontSize();\n      localStorage.setItem('fontSize', String(size));\n      document.documentElement.style.setProperty('--font-size-base', `${size}px`);\n    });\n  }\n}\n\n// ---- Creating an effect outside the constructor ----\n@Component({ selector: 'app-dynamic', standalone: true, template: '' })\nexport class DynamicComponent {\n  private injector = inject(Injector);\n  count = signal(0);\n\n  startTracking(): void {\n    // Pass injector explicitly when creating effects outside constructor\n    effect(() => {\n      console.log('Count changed:', this.count());\n    }, { injector: this.injector });\n  }\n}",
      "language": "typescript"
    },
    {
      "id": "signal-based-components",
      "title": "Signal-based inputs, outputs and model",
      "explanation": "\n          <p>Angular 17+ introduced signal-based alternatives to <code>@Input()</code>, <code>@Output()</code>, and two-way binding. These integrate component communication directly into the signal system, making the whole data flow — from parent to child, child to parent, and back — reactive without Zone.js.</p>\n\n          <h3>input() — Signal Inputs</h3>\n          <p>Instead of <code>@Input() productId!: number</code>, you write <code>productId = input.required&lt;number&gt;()</code>. The result is a read-only signal. Inside the component, you read it as <code>this.productId()</code>. It automatically participates in computed signals and effects — you can derive a computed value from an input signal without needing <code>ngOnChanges</code>. <code>input.required()</code> enforces that the parent must provide the value, just like <code>@Input({ required: true })</code>.</p>\n\n          <h3>output() — Signal Outputs</h3>\n          <p>Instead of <code>@Output() selected = new EventEmitter&lt;Product&gt;()</code>, you write <code>selected = output&lt;Product&gt;()</code>. You emit with <code>this.selected.emit(product)</code>. The parent template binds the same way: <code>(selected)=\"onSelect($event)\"</code>. Signal outputs are simpler because they do not extend <code>Subject</code> — they are pure event emitters with no observable overhead.</p>\n\n          <h3>model() — Two-Way Binding Signal</h3>\n          <p><code>model()</code> creates a writable signal that is also an input/output pair. The child reads and writes it as a regular signal. The parent binds with <code>[(value)]=\"parentProp\"</code> — the same two-way binding syntax as <code>ngModel</code>. When the child calls <code>this.value.set(newValue)</code>, the change propagates back to the parent automatically.</p>\n        ",
      "code": "import { Component, input, output, model, computed } from '@angular/core';\n\ninterface Product { id: number; name: string; price: number; }\n\n// ---- Child component using signal-based API ----\n@Component({\n  selector: 'app-product-card',\n  standalone: true,\n  template: `\n    <div class=\"card\">\n      <h3>{{ product().name }}</h3>\n      <p>${{ product().price }}</p>\n      <p>Qty: {{ quantity() }}</p>\n      <button (click)=\"quantity.set(quantity() + 1)\">+</button>\n      <button (click)=\"quantity.set(Math.max(1, quantity() - 1))\">-</button>\n      <button (click)=\"addToCart()\">Add to Cart</button>\n    </div>\n  `\n})\nexport class ProductCardComponent {\n  // input() — read-only signal, required from parent\n  product = input.required<Product>();\n\n  // input() with default — optional\n  maxQuantity = input<number>(10);\n\n  // model() — two-way binding: parent can read AND write this\n  quantity = model<number>(1);\n\n  // output() — pure event emitter\n  cartAdded = output<{ product: Product; quantity: number }>();\n\n  // Computed from input signal — reacts automatically when product changes\n  discountedPrice = computed(() => this.product().price * 0.9);\n\n  Math = Math; // expose to template\n\n  addToCart(): void {\n    this.cartAdded.emit({ product: this.product(), quantity: this.quantity() });\n    this.quantity.set(1); // reset\n  }\n}\n\n// ---- Parent using all three ----\n@Component({\n  selector: 'app-shop',\n  standalone: true,\n  imports: [ProductCardComponent],\n  template: `\n    <app-product-card\n      [product]=\"featuredProduct\"\n      [(quantity)]=\"selectedQty\"\n      (cartAdded)=\"handleCartAdd($event)\"\n    ></app-product-card>\n    <p>Selected quantity in parent: {{ selectedQty }}</p>\n  `\n})\nexport class ShopComponent {\n  featuredProduct: Product = { id: 1, name: 'Laptop', price: 999 };\n  selectedQty = 1;\n\n  handleCartAdd(event: { product: Product; quantity: number }): void {\n    console.log(`Added ${event.quantity}x ${event.product.name} to cart`);\n  }\n}",
      "language": "typescript"
    },
    {
      "id": "advanced-signal-apis",
      "title": "Advanced Signal APIs: toSignal, toObservable, linkedSignal, resource",
      "explanation": "\n          <p>Angular ships several utilities that bridge the signal and Observable worlds, making it practical to adopt signals incrementally in existing Observable-heavy codebases.</p>\n\n          <h3>toSignal() — Observable to Signal</h3>\n          <p><code>toSignal(observable$)</code> subscribes to an Observable and returns a signal that holds the latest emitted value. It automatically unsubscribes when the component is destroyed. The <code>initialValue</code> option sets the value before the first emission. Use this to convert HTTP responses, route params, and form value streams into signals that templates can read directly without <code>| async</code>.</p>\n\n          <h3>toObservable() — Signal to Observable</h3>\n          <p><code>toObservable(signal)</code> converts a signal into an Observable that emits whenever the signal changes. Use this when you need RxJS operators like <code>switchMap</code>, <code>debounceTime</code>, or <code>distinctUntilChanged</code> applied to signal changes — for example, triggering a debounced API call when a search signal changes.</p>\n\n          <h3>linkedSignal() — Resettable Derived Signal</h3>\n          <p><code>linkedSignal()</code> creates a writable signal whose value resets based on a source signal. Unlike <code>computed()</code> (which is always read-only), a <code>linkedSignal</code> can be written to locally but reverts to the derived value whenever the source changes. The classic use case is a selection that resets when the list it selects from changes.</p>\n\n          <h3>resource() — Async Data with Loading/Error State</h3>\n          <p><code>resource()</code> manages asynchronous data fetching declaratively. You provide a <code>request</code> signal and a <code>loader</code> function. Whenever the request changes, the loader runs automatically. The result is an object with <code>.value()</code>, <code>.isLoading()</code>, and <code>.error()</code> signals — replacing the boilerplate of BehaviorSubject + switchMap + loading flag patterns.</p>\n        ",
      "code": "import { Component, signal, computed, linkedSignal, resource, inject } from '@angular/core';\nimport { toSignal, toObservable } from '@angular/core/rxjs-interop';\nimport { HttpClient } from '@angular/common/http';\nimport { switchMap, debounceTime, distinctUntilChanged } from 'rxjs/operators';\n\n@Component({\n  selector: 'app-product-search',\n  standalone: true,\n  template: `\n    <input (input)=\"query.set($any($event.target).value)\" placeholder=\"Search...\" />\n\n    @if (results.isLoading()) {\n      <p>Searching...</p>\n    } @else if (results.error()) {\n      <p>Error: {{ results.error() }}</p>\n    } @else {\n      <p>Found {{ results.value()?.length ?? 0 }} products</p>\n      <div *ngFor=\"let p of results.value()\">\n        <strong (click)=\"selectedCategory.set(p.category)\">{{ p.name }}</strong>\n      </div>\n    }\n\n    <!-- linkedSignal: resets page to 1 whenever query changes -->\n    <p>Page {{ page() }}</p>\n    <button (click)=\"page.set(page() + 1)\">Next</button>\n  `\n})\nexport class ProductSearchComponent {\n  private http = inject(HttpClient);\n\n  query = signal('');\n  selectedCategory = signal<string | null>(null);\n\n  // linkedSignal: page resets to 1 whenever query changes,\n  // but can also be set directly (e.g., by Next button)\n  page = linkedSignal(() => {\n    this.query(); // dependency: reset when query changes\n    return 1;\n  });\n\n  // resource: manages async fetch with automatic loading/error states\n  results = resource({\n    // Re-fetches whenever query or page changes\n    request: () => ({ q: this.query(), p: this.page() }),\n    loader: ({ request }) =>\n      this.http.get<any[]>(`/api/products?q=${request.q}&page=${request.p}`)\n        .toPromise()\n  });\n\n  // toSignal + toObservable: debounce query changes before fetching\n  debouncedQuery = toSignal(\n    toObservable(this.query).pipe(\n      debounceTime(300),\n      distinctUntilChanged()\n    ),\n    { initialValue: '' }\n  );\n}",
      "language": "typescript"
    },
    {
      "id": "migration-from-observable-pattern",
      "title": "Migrating from Observable to Signal pattern",
      "explanation": "\n          <p>Signals and Observables can coexist in the same application. Angular's migration path is designed to be incremental — you do not need to rewrite everything at once. The bridging utilities <code>toSignal()</code> and <code>toObservable()</code> let you move the boundary between the two worlds wherever makes sense for your codebase.</p>\n\n          <h3>What Changes — What Stays the Same</h3>\n          <p>Keep Observables for data sources: HTTP calls, WebSockets, route params, form value changes. These are inherently asynchronous event streams, and RxJS operators handle them elegantly. Convert to signals at the component level with <code>toSignal()</code>. Replace local component state (<code>BehaviorSubject</code>s used only within a component) with writable signals. Replace <code>combineLatest</code> + <code>map</code> for derived UI values with <code>computed()</code>.</p>\n\n          <h3>Template Simplification</h3>\n          <p>The most visible change when migrating is template simplification. With Observables, every async value needs <code>| async</code> and an <code>*ngIf=\"data$ | async as data\"</code> wrapper to avoid null checks. With signals, you read the value directly: <code>{{ user()?.name }}</code>. No async pipe, no nesting.</p>\n\n          <h3>The New Control Flow Syntax</h3>\n          <p>Angular 17+ introduced built-in control flow blocks (<code>@if</code>, <code>@for</code>, <code>@switch</code>) that work naturally with signals. Combined with signal-based inputs, the new syntax removes the need for <code>NgIf</code>, <code>NgFor</code>, and <code>NgSwitch</code> imports in standalone components, and makes loading/error/data state patterns very clean.</p>\n        ",
      "code": "import { Component, signal, computed, inject } from '@angular/core';\nimport { toSignal } from '@angular/core/rxjs-interop';\nimport { HttpClient } from '@angular/common/http';\nimport { switchMap, catchError, of } from 'rxjs';\nimport { toObservable } from '@angular/core/rxjs-interop';\n\n// ---- BEFORE: Observable-heavy pattern ----\n// @Component({\n//   template: `\n//     <ng-container *ngIf=\"filteredItems$ | async as items\">\n//       <li *ngFor=\"let item of items\">{{ item.name }}</li>\n//     </ng-container>\n//   `\n// })\n// export class OldComponent {\n//   filter$ = new BehaviorSubject('');\n//   items$ = this.http.get<Item[]>('/api/items');\n//   filteredItems$ = combineLatest([this.items$, this.filter$]).pipe(\n//     map(([items, filter]) => items.filter(i => i.name.includes(filter)))\n//   );\n// }\n\n// ---- AFTER: Signal-first pattern ----\n@Component({\n  selector: 'app-item-list',\n  standalone: true,\n  template: `\n    <input (input)=\"filter.set($any($event.target).value)\" placeholder=\"Filter...\" />\n\n    @if (isLoading()) {\n      <p>Loading items...</p>\n    } @else if (error()) {\n      <p>Failed to load: {{ error() }}</p>\n    } @else {\n      @for (item of filteredItems(); track item.id) {\n        <li>{{ item.name }}</li>\n      } @empty {\n        <li>No items match your filter.</li>\n      }\n    }\n  `\n})\nexport class NewComponent {\n  private http = inject(HttpClient);\n\n  // Local state as writable signals\n  filter    = signal('');\n  isLoading = signal(true);\n  error     = signal<string | null>(null);\n\n  // Convert HTTP Observable to signal\n  items = toSignal(\n    this.http.get<{ id: number; name: string }[]>('/api/items').pipe(\n      catchError(err => {\n        this.error.set(err.message);\n        return of([]);\n      })\n    ),\n    {\n      initialValue: [],\n      // Called synchronously — marks loading complete\n      rejectErrors: false\n    }\n  );\n\n  // Derived state as computed — no RxJS needed\n  filteredItems = computed(() => {\n    this.isLoading.set(false); // mark loaded once items signal has a value\n    return this.items().filter(i =>\n      i.name.toLowerCase().includes(this.filter().toLowerCase())\n    );\n  });\n}",
      "language": "typescript"
    }
  ]
});
